// SPDX-FileCopyrightText: The Fission Authors
//
// SPDX-License-Identifier: Apache-2.0

package v1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh
// AUTO-GENERATED FUNCTIONS START HERE
var map_AgentConfig = map[string]string{
	"":                           "AgentConfig declares a function's agent behavior: session identity, idle/archive lifecycle policy, and the live-session quota. Presence of the enclosing FunctionSpec.Agent is the on switch — there is no separate enabled flag, so the in-memory zero value and the stored object never disagree (the same rationale as StreamingConfig).",
	"session":                    "Session, when non-nil, overrides where the session id comes from. nil (the default) means the X-Fission-Session request header.",
	"idleAfter":                  "IdleAfter is how long a session stays \"active\" after its last turn before the sweeper marks it idle (a status transition, not a pod operation — pods are released after every turn regardless). Must be >= 0; zero (or nil) means the platform default (5m).",
	"archiveAfter":               "ArchiveAfter is how long an idle session is kept listed, measured from its LastActiveAt, before it is archived (delisted; record retained on a retention TTL). Must be >= IdleAfter when both are set; zero (or nil) means the platform default (24h). The resolved value is always clamped up to at least the resolved IdleAfter, so no combination of defaults can archive a session while it is still within its idle window.",
	"maxSessions":                "MaxSessions caps live (active or idle) sessions for this agent, enforced atomically on session creation with the statestore's counted-write (the same quota mechanism as StateConfig.MaxKeys). Archived sessions live in a sibling keyspace and never count against this cap. 0 means unlimited.",
	"historyTrimBelowCheckpoint": "HistoryTrimBelowCheckpoint, when true, lets the agent runtime's sweeper trim this agent's session fact logs below each session's committed checkpoint coverage boundary (G13). Requires State: a knob that can never act (no state keyspace means no history) is rejected at admission.",
}

func (AgentConfig) SwaggerDoc() map[string]string {
	return map_AgentConfig
}

var map_AgentSessionConfig = map[string]string{
	"":       "AgentSessionConfig declares how the session id is derived from a request. Requests missing the id get a runtime-minted UUID, returned in the X-Fission-Session response header.",
	"source": "Source is where to look for the session id.",
	"name":   "Name is the header or query-parameter name holding the session id, e.g. \"X-Session-Id\". It must not be a reserved runtime header name (\"Authorization\" or the \"X-Fission-\" prefix, which the runtime owns): to use the platform default header (X-Fission-Session), leave the enclosing Session nil rather than naming it here.",
}

func (AgentSessionConfig) SwaggerDoc() map[string]string {
	return map_AgentSessionConfig
}

var map_AliasTargetRecord = map[string]string{
	"": "AliasTargetRecord is one entry in FunctionAliasStatus.History: a previously resolved target, kept for audit / rollback visibility.",
}

func (AliasTargetRecord) SwaggerDoc() map[string]string {
	return map_AliasTargetRecord
}

var map_Archive = map[string]string{
	"":          "Archive contains or references a collection of sources or binary files. The CEL rule below deliberately never references self.literal: any access to a byte-format field (even has()) makes the apiserver convert its base64 value for CEL using URL-safe decoding, which rejects any standard-base64 payload containing '/' or '+' — in practice every zipped literal archive. The literal/oci combination is instead rejected by the webhook (Archive.Validate), with the same message.",
	"type":      "Type defines how the package is specified: literal, URL, or OCI. Available value:\n - literal\n - url\n - oci",
	"literal":   "Literal contents of the package. Can be used for encoding packages below TODO (256 KB?) size.",
	"url":       "URL references a package.",
	"checksum":  "Checksum ensures the integrity of packages referenced by URL. Ignored for literals.",
	"oci":       "OCI references an OCI image holding the archive contents. Mutually exclusive with Literal and URL. Valid on both PackageSpec.Deployment and PackageSpec.Source (RFC-0031): a source OCI archive is pulled by the builder pod's fetcher, whose keychain resolves the builder pod's ServiceAccount imagePullSecrets plus the archive's ImagePullSecrets.",
	"secretref": "SecretRef names a Secret holding credentials for fetching URL. Keys: username+password (basic auth), token (bearer), headers (extra headers, one \"Name: Value\" per line). Like OCIArchive.ImagePullSecrets it is resolved in the namespace of the pod that performs the fetch: the function pod's namespace for deployment archives, the builder pod's namespace for source archives. Valid only for a url archive whose URL is not a storagesvc archive URL; credentials are attached only to requests to the URL's exact origin.",
}

func (Archive) SwaggerDoc() map[string]string {
	return map_Archive
}

var map_AuthLogin = map[string]string{
	"": "AuthLogin defines the body for router login",
}

func (AuthLogin) SwaggerDoc() map[string]string {
	return map_AuthLogin
}

var map_Builder = map[string]string{
	"":          "Builder is the setting for environment builder. Bounded podspec / container safety rules — see the matching Runtime block above.",
	"image":     "Image for containing the language compilation environment.",
	"command":   "(Optional) Default build command to run for this build environment.",
	"container": "(Optional) Container allows the modification of the deployed builder container using the Kubernetes Container spec. Fission overrides the following fields: - Name - Image; set to the Builder.Image - Command; set to the Builder.Command - TerminationMessagePath - ImagePullPolicy - ReadinessProbe",
	"podspec":   "PodSpec will store the spec of the pod that will be applied to the pod created for the builder",
}

func (Builder) SwaggerDoc() map[string]string {
	return map_Builder
}

var map_CanaryConfig = map[string]string{
	"": "CanaryConfig is for canary deployment of two functions.",
}

func (CanaryConfig) SwaggerDoc() map[string]string {
	return map_CanaryConfig
}

var map_CanaryConfigList = map[string]string{
	"": "CanaryConfigList is a list of CanaryConfigs.",
}

func (CanaryConfigList) SwaggerDoc() map[string]string {
	return map_CanaryConfigList
}

var map_CanaryConfigSpec = map[string]string{
	"":                 "CanaryConfigSpec defines the canary configuration spec",
	"trigger":          "HTTP trigger that this config references",
	"newfunction":      "New version of the function",
	"oldfunction":      "Old stable version of the function",
	"weightincrement":  "Weight increment step for function",
	"duration":         "Weight increment interval, string representation of time.Duration, ex : 1m, 2h, 2d (default: \"2m\")",
	"failurethreshold": "Threshold in percentage beyond which the new version of the function is considered unstable",
}

func (CanaryConfigSpec) SwaggerDoc() map[string]string {
	return map_CanaryConfigSpec
}

var map_CanaryConfigStatus = map[string]string{
	"":           "CanaryConfigStatus represents canary config status",
	"conditions": "Conditions represent the latest observations of the canary's state.",
}

func (CanaryConfigStatus) SwaggerDoc() map[string]string {
	return map_CanaryConfigStatus
}

var map_Checksum = map[string]string{
	"": "Checksum of package contents when the contents are stored outside the Package struct. Type is the checksum algorithm; \"sha256\" is the only currently supported one. Sum is hex encoded.",
}

func (Checksum) SwaggerDoc() map[string]string {
	return map_Checksum
}

var map_ConfigMapReference = map[string]string{
	"":          "ConfigMapReference is a reference to a kubernetes configmap.",
	"mountPath": "MountPath redirects this configmap's file projection from the default /configs/<namespace>/<name>; relative to the /configs root. See SecretReference.MountPath for the constraint rationale.",
}

func (ConfigMapReference) SwaggerDoc() map[string]string {
	return map_ConfigMapReference
}

var map_DestinationRef = map[string]string{
	"":         "DestinationRef routes an async invocation's result to exactly one target: a Function (invoked async through the same machinery, depth-capped) or a Topic (published to a message queue). Exactly one of Function/Topic must be set. Topic destinations on the built-in statestore provider are supported (RFC-0027); broker types are rejected by the webhook until the egress phase lands.",
	"function": "Function is a same-namespace function destination, invoked asynchronously with the result envelope as its body (depth-capped to stop runaway chains).",
	"topic":    "Topic publishes the result envelope to a message-queue topic.",
}

func (DestinationRef) SwaggerDoc() map[string]string {
	return map_DestinationRef
}

var map_Environment = map[string]string{
	"": "Environment is environment for building and running user functions.",
}

func (Environment) SwaggerDoc() map[string]string {
	return map_Environment
}

var map_EnvironmentList = map[string]string{
	"": "EnvironmentList is a list of Environments.",
}

func (EnvironmentList) SwaggerDoc() map[string]string {
	return map_EnvironmentList
}

var map_EnvironmentReference = map[string]string{
	"":     "EnvironmentReference is a reference to an environment. It is used by both FunctionSpec.Environment and PackageSpec.Environment.",
	"name": "Name of the referenced environment. Optional + omitempty: an unset reference is omitted and its Pattern skipped (a container function has no environment; a Package with an unset environment is admitted and fails later with a clear builder error — the fission CLI still rejects it). When set, it must be a DNS-1123 label.",
}

func (EnvironmentReference) SwaggerDoc() map[string]string {
	return map_EnvironmentReference
}

var map_EnvironmentSpec = map[string]string{
	"":                             "EnvironmentSpec contains with builder, runtime and some other related environment settings.",
	"version":                      "Version is the Environment API version\n\nVersion \"1\" allows user to run code snippet in a file, and it's supported by most of the environments except tensorflow-serving.\n\nVersion \"2\" supports downloading and compiling user function if source archive is not empty.\n\nVersion \"3\" is almost the same with v2, but you're able to control the size of pre-warm pool of the environment.",
	"runtime":                      "Runtime is configuration for running function, like container image etc.",
	"builder":                      "(Optional) Builder is configuration for builder manager to launch environment builder to build source code into deployable binary.",
	"allowedFunctionsPerContainer": "(Optional) defaults to 'single'. Fission workflow uses 'infinite' to load multiple functions in one function pod. Available value: - single - infinite",
	"allowAccessToExternalNetwork": "Istio default blocks all egress traffic for safety. To enable accessibility of external network for builder/function pod, set to 'true'. (Optional) defaults to 'false'",
	"resources":                    "The request and limit CPU/MEM resource setting for poolmanager to set up pods in the pre-warm pool. (Optional) defaults to no limitation.",
	"poolsize":                     "The initial pool size for environment",
	"terminationGracePeriod":       "The grace time for pod to perform connection draining before termination. The unit is in seconds. A terminating function pod keeps serving for the WHOLE grace window (the preStop hook sleeps through it, then the kubelet kills the pod), so this value is exactly how long every teardown — idle reap, env update roll, upgrade, node drain — takes per pod. 90s covers endpoint propagation (seconds) plus the 60s default function timeout with margin, mirroring the router's own 75s-drain/90s-grace posture; set it per environment for functions with longer request timeouts.\n\nThe CRD default below is what makes the documented default true for API-created Environments: nil means \"use the default\" and the apiserver fills an absent field with 90 at serving time.\n\nThe *pointer* is what makes an EXPLICIT 0 (\"no drain window, kill instantly\") expressible from typed Go clients: on the previous int64 field, omitempty marshalled 0 as absent and the apiserver served it back as 90, so raw YAML was the only way to say 0. In-process readers must use EffectiveTerminationGracePeriod() (env_validation.go), which mirrors the CRD default for objects that never crossed the apiserver. (Optional) defaults to 90 seconds",
	"keeparchive":                  "KeepArchive is used by fetcher to determine if the extracted archive or unarchived file should be placed, which is then used by specialize handler. (This is mainly for the JVM environment because .jar is one kind of zip archive.)",
	"imagepullsecret":              "ImagePullSecret is the secret for Kubernetes to pull an image from a private registry.",
	"runtimeClassName":             "(Optional) RuntimeClassName opts this environment's pods into a syscall-isolating RuntimeClass — for example gVisor's \"gvisor\" or Kata Containers' \"kata\" — instead of the node's default (typically runc) container runtime. It applies to BOTH this environment's runtime (warm pool / specialized) pods AND its builder pods: an author opting into isolation means \"this env's workloads,\" and builder pods run user build commands, arguably more arbitrary-code-shaped than the runtime pods.\n\nThis is fill-if-nil only: a RuntimeClassName set directly on Runtime.PodSpec (or Builder.PodSpec) is the documented full override escape hatch and always takes precedence over this field when both are set.\n\nNOT applied to container-executor functions (Tier C) — there is no Environment in scope on that path today, consistent with how Runtime.PodSpec/Builder.PodSpec are already handled.\n\nThe referenced RuntimeClass object is not required to exist at admission time; an absent one fails at pod scheduling, not here.",
}

func (EnvironmentSpec) SwaggerDoc() map[string]string {
	return map_EnvironmentSpec
}

var map_EnvironmentStatus = map[string]string{
	"": "EnvironmentStatus describes the observed state of an Environment.",
}

func (EnvironmentStatus) SwaggerDoc() map[string]string {
	return map_EnvironmentStatus
}

var map_ExecutionStrategy = map[string]string{
	"":                      "ExecutionStrategy specifies low-level parameters for function execution, such as the number of instances.\n\nMinScale affects the cold start behavior for a function. If MinScale is 0 then the deployment is created on first invocation of function and is good for requests of asynchronous nature. If MinScale is greater than 0 then MinScale number of pods are created at the time of creation of function. This ensures faster response during first invocation at the cost of consuming resources.\n\nMaxScale is the maximum number of pods that function will scale to based on TargetCPUPercent and resources allocated to the function pod.",
	"ExecutorType":          "ExecutorType is the executor type of function used. Defaults to \"poolmgr\".\n\nAvailable value:\n - poolmgr\n - newdeploy\n - container",
	"MinScale":              "This is only for newdeploy to set up minimum replicas of deployment.",
	"MaxScale":              "This is only for newdeploy to set up maximum replicas of deployment.",
	"TargetCPUPercent":      "Deprecated: use hpaMetrics instead. This is only for executor type newdeploy and container to set up target CPU utilization of HPA. Applicable for executor type newdeploy and container.",
	"SpecializationTimeout": "This is the timeout setting for executor to wait for pod specialization.",
	"hpaMetrics":            "hpaMetrics is the list of metrics used to determine the desired replica count of the Deployment created for the function. Applicable for executor type newdeploy and container.",
	"hpaBehavior":           "hpaBehavior is the behavior of HPA when scaling in up/down direction. Applicable for executor type newdeploy and container.",
}

func (ExecutionStrategy) SwaggerDoc() map[string]string {
	return map_ExecutionStrategy
}

var map_FissionTenant = map[string]string{
	"": "FissionTenant onboards a Kubernetes namespace for Fission. It is the cluster-scoped source of truth the tenant-lifecycle controller reconciles into the live resource-namespace set (and, in later phases, per-namespace RBAC, service accounts, and auth keys). Setting the label fission.io/enabled=true on a Namespace is sugar the controller materializes into one of these. See docs/multiple-namespace/prd.md.",
}

func (FissionTenant) SwaggerDoc() map[string]string {
	return map_FissionTenant
}

var map_FissionTenantList = map[string]string{
	"": "FissionTenantList is a list of FissionTenants.",
}

func (FissionTenantList) SwaggerDoc() map[string]string {
	return map_FissionTenantList
}

var map_FissionTenantSpec = map[string]string{
	"":                  "FissionTenantSpec declares which namespace Fission manages and, optionally, where that tenant's function and builder workloads run.",
	"namespace":         "Namespace is the Kubernetes namespace this tenant onboards. It is the immutable join key to the live Namespace.",
	"functionNamespace": "FunctionNamespace, if set, is where this tenant's function pods and Services run; empty means they run in spec.namespace. Generalizes the deprecated cluster-global FISSION_FUNCTION_NAMESPACE to a per-tenant mapping.",
	"builderNamespace":  "BuilderNamespace, if set, is where this tenant's builder pods run; empty means they run in spec.namespace.",
}

func (FissionTenantSpec) SwaggerDoc() map[string]string {
	return map_FissionTenantSpec
}

var map_FissionTenantStatus = map[string]string{
	"":                   "FissionTenantStatus reports the controller's progress onboarding the tenant.",
	"observedGeneration": "ObservedGeneration is the spec generation the controller last reconciled.",
	"conditions":         "Conditions are the latest observations of the tenant's state: RBACProvisioned, ServiceAccountsReady, AuthKeyProvisioned, WatchActive, and the Ready rollup.",
}

func (FissionTenantStatus) SwaggerDoc() map[string]string {
	return map_FissionTenantStatus
}

var map_Function = map[string]string{
	"": "Function is function runs within environment runtime with given package and secrets/configmaps.",
}

func (Function) SwaggerDoc() map[string]string {
	return map_Function
}

var map_FunctionAlias = map[string]string{
	"": "FunctionAlias is a mutable, named pointer at one (or, during a weighted rollout, two) FunctionVersion(s) of a Function (RFC-0025). Aliases are what triggers reference in production; moving an alias is how a rollout or rollback happens without touching the trigger.",
}

func (FunctionAlias) SwaggerDoc() map[string]string {
	return map_FunctionAlias
}

var map_FunctionAliasList = map[string]string{
	"": "FunctionAliasList is a list of FunctionAliases.",
}

func (FunctionAliasList) SwaggerDoc() map[string]string {
	return map_FunctionAliasList
}

var map_FunctionAliasSpec = map[string]string{
	"":                 "Repo convention (types.go:755,778,955): guard BOTH absent and explicit-empty on optional strings.",
	"version":          "Version pins by FunctionVersion name (imperative path). XOR PackageDigest.",
	"packageDigest":    "PackageDigest pins declaratively (GitOps): resolved asynchronously to the FunctionVersion that recorded this digest; eventually consistent.",
	"weight":           "Weight (0-100) served by the primary target; nil = 100%.",
	"secondaryVersion": "SecondaryVersion receives 100-Weight. Name-pinned only.",
}

func (FunctionAliasSpec) SwaggerDoc() map[string]string {
	return map_FunctionAliasSpec
}

var map_FunctionAliasStatus = map[string]string{
	"":                "FunctionAliasStatus describes the observed state of a FunctionAlias.",
	"resolvedVersion": "ResolvedVersion is the FunctionVersion name this alias currently resolves to (always name-pinned, even when Spec.PackageDigest declares the target declaratively).",
	"history":         "History is a bounded tail of previously resolved targets, most recent last.",
}

func (FunctionAliasStatus) SwaggerDoc() map[string]string {
	return map_FunctionAliasStatus
}

var map_FunctionList = map[string]string{
	"": "FunctionList is a list of Functions.",
}

func (FunctionList) SwaggerDoc() map[string]string {
	return map_FunctionList
}

var map_FunctionPackageRef = map[string]string{
	"":             "FunctionPackageRef includes the reference to the package also the entrypoint of package.",
	"packageref":   "Package reference",
	"functionName": "FunctionName specifies a specific function within the package. This allows functions to share packages, by having different functions within the same package.\n\nFission itself does not interpret this path. It is passed verbatim to build and runtime environments.\n\nThis is optional: if unspecified, the environment has a default name.",
}

func (FunctionPackageRef) SwaggerDoc() map[string]string {
	return map_FunctionPackageRef
}

var map_FunctionReference = map[string]string{
	"":                "FunctionReference refers to a function",
	"type":            "Type indicates whether this function reference is by name or selector. For now, the only supported reference type is by \"name\".  Future reference types:\n  * Function by label or annotation\n  * Branch or tag of a versioned function\n  * A \"rolling upgrade\" from one version of a function to another\nAvailable value: - name - function-weights",
	"name":            "Name of the function. Bounded to a DNS-1123 label length: the CEL rule on this type needs the schema bound so the apiserver's cost estimator can price the regex — without it, embedding the type under a map (WorkflowSpec.States) blows the per-CRD cost budget.",
	"alias":           "Alias, when set, targets a FunctionAlias by name instead of the live Function directly (RFC-0025): the alias is a movable pointer that the router resolves at request time to whatever FunctionVersion it currently points at, so repointing the alias (e.g. for a canary rollout or a rollback) redirects traffic without touching this reference. Valid only when Type is \"name\"; mutually exclusive with Version. Empty (the default) preserves today's behavior: route straight to the live Function.",
	"version":         "Version, when set, pins this reference to one FunctionVersion CR by name (RFC-0025) — an immutable published snapshot that never moves, unlike Alias. Valid only when Type is \"name\"; mutually exclusive with Alias. Empty (the default) preserves today's behavior: route straight to the live Function.",
	"functionweights": "Function Reference by weight. this map contains function name as key and its weight as the value. This is for canary upgrade purpose.",
}

func (FunctionReference) SwaggerDoc() map[string]string {
	return map_FunctionReference
}

var map_FunctionSpec = map[string]string{
	"":                       "FunctionSpec describes the contents of the function. Bounded podspec safety rules — CEL admission gate for the simple pod-level invariants. Per-container SecurityContext checks stay in the webhook (ValidatePodSpecSafety) because iterating containers exceeds the CEL cost budget; the rules here cover only the bounded, cheap cases. The has() guards on each scalar are required: PodSpec's bool/string fields are json:\"...,omitempty\" so a zero/empty value is OMITTED from the object, and CEL errors with \"no such key\" if the rule accesses an absent field.",
	"environment":            "Environment is the build and runtime environment that this function is associated with. An Environment with this name should exist, otherwise the function cannot be invoked.",
	"package":                "Reference to a package containing deployment and optionally the source.",
	"secrets":                "Reference to a list of secrets.",
	"configmaps":             "Reference to a list of configmaps.",
	"env":                    "Env lists per-function environment variables set on the function's runtime container: literals, plus key-level references into same-namespace Secrets/ConfigMaps via valueFrom (secretKeyRef / configMapKeyRef only — fieldRef and resourceFieldRef are rejected at admission because poolmgr's specialize-time injection cannot honor pod-level field refs portably; RFC-0030 §1). Function Env wins over EnvFrom, which wins over the environment podspec's merged env. Platform-reserved names (FISSION_*, RESOURCE_VERSION_COUNT, and the interpreter/proxy-hijack set) are denied at admission and enforced at injection. Additive and backward compatible.",
	"envFrom":                "EnvFrom projects whole same-namespace Secrets/ConfigMaps into the function's environment, with an optional prefix; later sources win over earlier ones (Kubernetes semantics), and function Env literals win over all EnvFrom keys.\n\nTwo phase-1 limits, both inherent to native (kubelet) injection: the kubelet expands envFrom BEFORE container env, so a name the environment podspec sets as a literal still beats an EnvFrom-supplied key of the same name; and reserved platform names appearing as data keys of a referenced object are not filtered (they are unknowable at admission and mutable afterwards) — they are only shadowed by the platform vars actually present on the container. Key-level filtering and full precedence arrive with the poolmgr phase, which resolves values itself. Additive and backward compatible.",
	"resources":              "cpu and memory resources as per K8S standards This is only for newdeploy to set up resource limitation when creating deployment for a function.",
	"InvokeStrategy":         "InvokeStrategy is a set of controls which affect how function executes",
	"functionTimeout":        "FunctionTimeout provides a maximum amount of duration within which a request for a particular function execution should be complete. This is optional. If not specified default value will be taken as 60s",
	"idletimeout":            "IdleTimeout specifies the length of time that a function is idle before the function pod(s) are eligible for deletion. If no traffic to the function is detected within the idle timeout, the executor will then recycle the function pod(s) to release resources.",
	"streaming":              "Streaming opts this function into the router's streaming invocation path: incremental flushing, an idle/max timeout split, and a router-driven pod keepalive for the connection's lifetime. When nil (the default) the function uses the classic buffered, retry-on-transient-error proxy path with a single FunctionTimeout deadline. Additive and backward compatible.",
	"tool":                   "Tool, when non-nil, advertises this function as a Model Context Protocol (MCP) tool on the fission-bundle --mcpPort server. The MCP server watches Function CRDs and hot-updates its tool list from this field. Presence is the on switch (like Streaming): nil (the default) means the function is never advertised as a tool. Additive and backward compatible.",
	"state":                  "State, when non-nil, opts this function into the RFC-0023 keyed-state API: a scoped statesvc keyspace backed by the RFC-0021 statestore, with a per-function token injected at specialization time. Presence is the on switch (like Streaming and Tool): nil (the default) means exactly today's behavior. Additive and backward compatible.",
	"invocation":             "Invocation, when non-nil, tunes RFC-0024 asynchronous invocation (X-Fission-Invoke-Mode: async) for this function: the durable retry policy and the maximum event age before an undelivered invocation is dead-lettered. A function without it still accepts async mode with platform defaults; this field only tunes them. Additive and backward compatible.",
	"concurrency":            "Maximum number of pods to be specialized which will serve requests This is optional. If not specified default value will be taken as 500",
	"requestsPerPod":         "RequestsPerPod indicates the maximum number of concurrent requests that can be served by a specialized pod This is optional. If not specified default value will be taken as 1",
	"onceOnly":               "OnceOnly specifies if specialized pod will serve exactly one request in its lifetime and would be garbage collected after serving that one request This is optional. If not specified default value will be taken as false",
	"retainPods":             "RetainPods specifies the number of specialized pods that should be retained after serving requests This is optional. If not specified default value will be taken as 0",
	"provisionedConcurrency": "ProvisionedConcurrency, when non-nil, opts this function into eager pre-warming of specialized pods (RFC-0026). The executor's provisioner keeps at least the configured Target specialized pods warm, published to the function's headless Service, and exempt from the idle reaper. nil (the default) is the classic on-demand cold-start path. Additive and backward compatible. Only valid when InvokeStrategy.ExecutionStrategy.ExecutorType is poolmgr.",
	"versioning":             "Versioning, when non-nil, opts this function into RFC-0025 immutable version snapshots and named aliases. Presence is the on switch (like Streaming and Tool): nil (the default) means exactly today's mutable in-place behavior. Additive and backward compatible.",
	"agent":                  "Agent, when non-nil, declares this function as an agent: its invocations are session-scoped, dispatched and lifecycle-tracked by the fission-bundle --agentPort subsystem, with session records kept in the statestore (never CRDs). Presence is the on switch (like Streaming, Tool and State): nil (the default) means exactly today's behavior. Additive and backward compatible.",
	"podspec":                "Podspec specifies podspec to use for executor type container based functions Different arguments mentioned for container based function are populated inside a pod.",
}

func (FunctionSpec) SwaggerDoc() map[string]string {
	return map_FunctionSpec
}

var map_FunctionStatus = map[string]string{
	"":                      "FunctionStatus describes the observed state of a Function.",
	"observedGeneration":    "ObservedGeneration reflects the .metadata.generation that the controller observed when it last updated the status.",
	"provisionedReady":      "ProvisionedReady is the number of warm specialized pods the provisioner is currently maintaining for this function (RFC-0026). Only meaningful when Spec.ProvisionedConcurrency is non-nil. Reported by the executor's provisioner on each reconcile pass.",
	"provisionedTarget":     "ProvisionedTarget is the effective target the provisioner is currently aiming for (base Target, or a schedule-window override in PR 2). Lets `fission fn get` show \"3/5 provisioned pods ready\".",
	"provisionedSpecTarget": "ProvisionedSpecTarget is the raw Target from spec (before the namespace cap clamp). When ProvisionedSpecTarget > ProvisionedTarget, the provisioner clamped the target to the namespace cap (executor.provisionedConcurrency.maxPerFunction) and the Provisioned condition carries reason ProvisionedClamped. Lets `fission fn get` show the spec-vs-effective divergence.",
	"conditions":            "Conditions represent the latest observations of the function's state.",
}

func (FunctionStatus) SwaggerDoc() map[string]string {
	return map_FunctionStatus
}

var map_FunctionVersion = map[string]string{
	"": "FunctionVersion is an immutable snapshot of a Function's spec at publish time (RFC-0025). Versions are minted by the version-control loop (auto mode) or `fission fn publish` (manual mode) and are never mutated after creation — only garbage collected once unreferenced by any FunctionAlias and beyond the retain floor. FunctionVersion carries no Status: its content is fixed at creation, so there is nothing to reconcile.",
}

func (FunctionVersion) SwaggerDoc() map[string]string {
	return map_FunctionVersion
}

var map_FunctionVersionList = map[string]string{
	"": "FunctionVersionList is a list of FunctionVersions.",
}

func (FunctionVersionList) SwaggerDoc() map[string]string {
	return map_FunctionVersionList
}

var map_FunctionVersionSpec = map[string]string{
	"":                      "FunctionVersionSpec is the immutable snapshot recorded by one publish.",
	"functionUID":           "FunctionUID and FunctionGeneration pin the executor identity of this snapshot: (UID, Generation) is the pool/cache key (crd.CacheKeyUG), so a version is a generation pin, not a new identity.",
	"snapshot":              "Snapshot is the function spec at publish time with Versioning zeroed (never nested) and, for legacy packages, PackageRef repointed at the version-owned snapshot Package.",
	"packageDigest":         "PackageDigest pins content: the OCI digest or sha256:<archive checksum>.",
	"envObservedGeneration": "Environment observation at publish time (observational, not pinning).",
}

func (FunctionVersionSpec) SwaggerDoc() map[string]string {
	return map_FunctionVersionSpec
}

var map_GatewayParentRef = map[string]string{
	"":            "GatewayParentRef references a Gateway (and optionally a specific listener) that the generated HTTPRoute attaches to. It mirrors the subset of gateway.networking.k8s.io ParentReference that Fission needs.",
	"name":        "Name of the parent Gateway.",
	"namespace":   "Namespace of the parent Gateway. Defaults to the router's namespace when empty. A non-empty, different namespace needs a ReferenceGrant.",
	"sectionName": "SectionName selects a specific listener on the Gateway. Empty attaches to all compatible listeners.",
	"port":        "Port narrows attachment to a specific Gateway listener port.",
}

func (GatewayParentRef) SwaggerDoc() map[string]string {
	return map_GatewayParentRef
}

var map_GatewayRouteConfig = map[string]string{
	"":           "GatewayRouteConfig is the Gateway-API-specific portion of a RouteConfig.",
	"parentRefs": "ParentRefs are the Gateways the generated HTTPRoute attaches to. The referenced Gateways are owned by the cluster operator (Fission does not create Gateways or GatewayClasses). A cross-namespace parentRef requires a ReferenceGrant in the Gateway's namespace.",
}

func (GatewayRouteConfig) SwaggerDoc() map[string]string {
	return map_GatewayRouteConfig
}

var map_HTTPTrigger = map[string]string{
	"": "HTTPTrigger is the trigger invokes user functions when receiving HTTP requests.",
}

func (HTTPTrigger) SwaggerDoc() map[string]string {
	return map_HTTPTrigger
}

var map_HTTPTriggerCorsConfig = map[string]string{
	"":                 "HTTPTriggerCorsConfig is the per-HTTPTrigger CORS allowlist. It is consumed by the router public listener to attach a CORS middleware to the trigger's route. Triggers without a CorsConfig receive no Access-Control-* response headers and therefore deny cross-origin browser reads at the Same-Origin Policy layer.",
	"allowOrigins":     "AllowOrigins is the list of allowed origins (scheme + host + port). Use [\"*\"] to allow any origin. Mixing \"*\" with AllowCredentials=true is a configuration error and is rejected by validation; browsers refuse the response in that combination.",
	"allowMethods":     "AllowMethods is the list of HTTP methods echoed in the Access-Control-Allow-Methods preflight response. When empty the trigger's existing Methods field is used.",
	"allowHeaders":     "AllowHeaders is the list of request headers the browser is allowed to send, echoed in Access-Control-Allow-Headers.",
	"exposeHeaders":    "ExposeHeaders is the list of response headers exposed to the browser, set in Access-Control-Expose-Headers.",
	"allowCredentials": "AllowCredentials sets Access-Control-Allow-Credentials. When true, AllowOrigins MUST NOT contain \"*\".",
	"maxAge":           "MaxAge is the preflight cache lifetime as parsed by time.ParseDuration. Empty means the header is omitted.",
}

func (HTTPTriggerCorsConfig) SwaggerDoc() map[string]string {
	return map_HTTPTriggerCorsConfig
}

var map_HTTPTriggerList = map[string]string{
	"": "HTTPTriggerList is a list of HTTPTriggers",
}

func (HTTPTriggerList) SwaggerDoc() map[string]string {
	return map_HTTPTriggerList
}

var map_HTTPTriggerSpec = map[string]string{
	"":               "HTTPTriggerSpec is for router to expose user functions at the given URL path.",
	"host":           "Deprecated: the original idea of this field is not for setting Ingress. Since we have IngressConfig now, remove Host after couple releases.",
	"relativeurl":    "RelativeURL is the exposed URL for external client to access a function with.",
	"prefix":         "Prefix with which functions are exposed. NOTE: Prefix takes precedence over URL/RelativeURL. Note that it does not treat slashes specially (\"/foobar/\" will be matched by the prefix \"/foobar\").",
	"keepPrefix":     "When function is exposed with Prefix based path, keepPrefix decides whether to keep or trim prefix in URL while invoking function.",
	"method":         "Use Methods instead of Method. This field is going to be deprecated in a future release HTTP method to access a function.",
	"methods":        "HTTP methods to access a function",
	"invocationMode": "InvocationMode, when \"async\", forces every request to this trigger into RFC-0024 asynchronous invocation even without the X-Fission-Invoke-Mode header (webhooks from third parties cannot set headers). \"\" (the default) leaves the per-request header in control.",
	"functionref":    "FunctionReference is a reference to the target function.",
	"createingress":  "If CreateIngress is true, router will create an ingress definition. Deprecated: the Kubernetes Ingress API is frozen. Use RouteConfig (with Provider \"gateway\") to expose functions through the Gateway API instead. CreateIngress + IngressConfig keep working for the deprecation window but will be removed in a future release.",
	"ingressconfig":  "IngressConfig for router to set up Ingress. Deprecated: superseded by RouteConfig. See CreateIngress.",
	"routeConfig":    "RouteConfig declares how the router exposes this trigger through an external route provider (Ingress or the Gateway API). It is the provider-neutral successor to CreateIngress + IngressConfig: when set it takes precedence over those fields. Leave nil to expose the function only through the router's own URL.",
	"corsConfig":     "CorsConfig configures CORS response headers for browser callers of this trigger. When nil, the router emits no Access-Control-* headers and the browser's Same-Origin Policy enforces cluster isolation from cross-origin pages (the deny-by-default behaviour). Set this field to allowlist specific origins for SPAs that legitimately call this trigger cross-origin.",
}

func (HTTPTriggerSpec) SwaggerDoc() map[string]string {
	return map_HTTPTriggerSpec
}

var map_HTTPTriggerStatus = map[string]string{
	"": "HTTPTriggerStatus describes the observed state of an HTTPTrigger.",
}

func (HTTPTriggerStatus) SwaggerDoc() map[string]string {
	return map_HTTPTriggerStatus
}

var map_IngressConfig = map[string]string{
	"":            "IngressConfig is for router to set up Ingress. Deprecated: superseded by RouteConfig. The Kubernetes Ingress API is frozen; use RouteConfig with Provider \"gateway\" for new triggers.",
	"annotations": "Annotations will be added to metadata when creating Ingress.",
	"path":        "Path is for path matching. The format of path depends on what ingress controller you used.",
	"host":        "Host is for ingress controller to apply rules. If host is empty or \"*\", the rule applies to all inbound HTTP traffic.",
	"tls":         "TLS is for user to specify a Secret that contains TLS key and certificate. The domain name in the key and crt must match the value of Host field.",
}

func (IngressConfig) SwaggerDoc() map[string]string {
	return map_IngressConfig
}

var map_InvocationConfig = map[string]string{
	"":          "InvocationConfig tunes RFC-0024 asynchronous invocation for a function. Presence of the enclosing FunctionSpec.Invocation is optional — a function without it still accepts async mode (X-Fission-Invoke-Mode: async) with platform defaults; this struct only tunes them. Field bounds are validated in Go (InvocationConfig.Validate, run at admission via validateForAdmission), not CEL, because metav1.Duration CEL rules are unproven in this CRD. An external dead-letter target is a later RFC-0024 phase.",
	"retry":     "Retry is the durable delivery retry policy. The zero value means platform defaults (a bounded exponential backoff over DefaultMaxAttempts attempts).",
	"maxAge":    "MaxAge caps how long an invocation may wait for successful delivery, measured from its enqueue time; once exceeded it is dead-lettered with reason \"expired\". nil means the platform default. Must be > 0 when set.",
	"onSuccess": "OnSuccess, when set, invokes a destination with a Lambda-shaped result envelope after the invocation is delivered successfully (2xx).",
	"onFailure": "OnFailure, when set, invokes a destination with the result envelope after the invocation permanently fails (a non-retryable 4xx, the retry budget spent, or MaxAge exceeded).",
}

func (InvocationConfig) SwaggerDoc() map[string]string {
	return map_InvocationConfig
}

var map_InvokeStrategy = map[string]string{
	"":                  "InvokeStrategy is a set of controls over how the function executes. It affects the performance and resource usage of the function.\n\nAn InvokeStrategy is of one of two types: ExecutionStrategy, which controls low-level parameters such as which ExecutorType to use, when to autoscale, minimum and maximum number of running instances, etc. A higher-level AbstractInvokeStrategy will also be supported; this strategy would specify the target request rate of the function, the target latency statistics, and the target cost (in terms of compute resources).",
	"ExecutionStrategy": "ExecutionStrategy specifies low-level parameters for function execution, such as the number of instances.",
	"StrategyType":      "StrategyType is the strategy type of function. Now it only supports 'execution'.",
}

func (InvokeStrategy) SwaggerDoc() map[string]string {
	return map_InvokeStrategy
}

var map_KubernetesWatchTrigger = map[string]string{
	"": "KubernetesWatchTrigger watches kubernetes resource events and invokes functions.",
}

func (KubernetesWatchTrigger) SwaggerDoc() map[string]string {
	return map_KubernetesWatchTrigger
}

var map_KubernetesWatchTriggerList = map[string]string{
	"": "KubernetesWatchTriggerList is a list of KubernetesWatchTriggers",
}

func (KubernetesWatchTriggerList) SwaggerDoc() map[string]string {
	return map_KubernetesWatchTriggerList
}

var map_KubernetesWatchTriggerSpec = map[string]string{
	"":              "KubernetesWatchTriggerSpec defines spec of KuberenetesWatchTrigger",
	"type":          "Type of resource to watch (Pod, Service, etc.)",
	"labelselector": "Resource labels",
	"functionref":   "The reference to a function for kubewatcher to invoke with when receiving events.",
}

func (KubernetesWatchTriggerSpec) SwaggerDoc() map[string]string {
	return map_KubernetesWatchTriggerSpec
}

var map_KubernetesWatchTriggerStatus = map[string]string{
	"": "KubernetesWatchTriggerStatus describes the observed state of a KubernetesWatchTrigger.",
}

func (KubernetesWatchTriggerStatus) SwaggerDoc() map[string]string {
	return map_KubernetesWatchTriggerStatus
}

var map_MessageQueueTrigger = map[string]string{
	"": "MessageQueueTrigger invokes functions when messages arrive to certain topic that trigger subscribes to.",
}

func (MessageQueueTrigger) SwaggerDoc() map[string]string {
	return map_MessageQueueTrigger
}

var map_MessageQueueTriggerList = map[string]string{
	"": "MessageQueueTriggerList is a list of MessageQueueTriggers.",
}

func (MessageQueueTriggerList) SwaggerDoc() map[string]string {
	return map_MessageQueueTriggerList
}

var map_MessageQueueTriggerSpec = map[string]string{
	"":                 "MessageQueueTriggerSpec defines a binding from a topic in a message queue to a function.",
	"functionref":      "The reference to a function for message queue trigger to invoke with when receiving messages from subscribed topic.",
	"messageQueueType": "Type of message queue (NATS, Kafka, AzureQueue)",
	"topic":            "Subscribed topic",
	"respTopic":        "Topic for message queue trigger to sent response from function.",
	"errorTopic":       "Topic to collect error response sent from function",
	"maxRetries":       "Maximum times for message queue trigger to retry",
	"contentType":      "Content type of payload",
	"pollingInterval":  "The period to check each trigger source on every ScaledObject, and scale the deployment up or down accordingly",
	"cooldownPeriod":   "The period to wait after the last trigger reported active before scaling the deployment back to 0",
	"minReplicaCount":  "Minimum number of replicas KEDA will scale the deployment down to",
	"maxReplicaCount":  "Maximum number of replicas KEDA will scale the deployment up to",
	"metadata":         "ScalerTrigger fields",
	"secret":           "Secret name",
	"mqtkind":          "Kind of Message Queue Trigger to be created, by default its fission",
	"podspec":          "(Optional) Podspec allows modification of deployed runtime pod with Kubernetes PodSpec The merging logic is briefly described below and detailed MergePodSpec function - Volumes mounts and env variables for function and fetcher container are appended - All additional containers and init containers are appended - Volume definitions are appended - Lists such as tolerations, ImagePullSecrets, HostAliases are appended - Structs are merged and variables from pod spec take precedence",
}

func (MessageQueueTriggerSpec) SwaggerDoc() map[string]string {
	return map_MessageQueueTriggerSpec
}

var map_MessageQueueTriggerStatus = map[string]string{
	"": "MessageQueueTriggerStatus describes the observed state of a MessageQueueTrigger.",
}

func (MessageQueueTriggerStatus) SwaggerDoc() map[string]string {
	return map_MessageQueueTriggerStatus
}

var map_OCIArchive = map[string]string{
	"":                 "OCIArchive references an OCI image whose flattened filesystem contains the deployment code (RFC-0001). The environment runtime image stays the pod's main container; only how the code reaches the shared volume changes.",
	"image":            "Image is a fully qualified OCI reference: registry/repo:tag[@digest].",
	"imagePullSecrets": "ImagePullSecrets are resolved when pulling the image. The fetcher-pull path passes them to the in-fetcher keychain; the image-volume path sets them on pod.Spec.ImagePullSecrets. They must exist in the namespace the function pods run in — the function's own namespace, or the configured function namespace for default-namespace functions.",
	"subPath":          "SubPath points at the deployment root inside the image filesystem, as a clean relative path; empty means the image root. It must be a directory: the image-volume path mounts it via the pod volumeMount subPath, and kubelets reject file subpaths on image volumes.",
	"digest":           "Digest is an optional content hash validated on pull.",
}

func (OCIArchive) SwaggerDoc() map[string]string {
	return map_OCIArchive
}

var map_Package = map[string]string{
	"":       "Package Think of these as function-level images.",
	"status": "Status indicates the build status of package.",
}

func (Package) SwaggerDoc() map[string]string {
	return map_Package
}

var map_PackageList = map[string]string{
	"": "PackageList is a list of Packages.",
}

func (PackageList) SwaggerDoc() map[string]string {
	return map_PackageList
}

var map_PackageRef = map[string]string{
	"":                "PackageRef is a reference to the package.",
	"name":            "The package reference is optional, so Name is omitempty: when unset it is omitted from the object and the Pattern below is skipped (a function may legitimately have no package). A present name must be a DNS-1123 label. A leaf Pattern (cheap structural validation) is used rather than a spec-level CEL matches() (which would exceed the cost budget).",
	"resourceversion": "Including resource version in the reference forces the function to be updated on package update, making it possible to cache the function based on its metadata.",
}

func (PackageRef) SwaggerDoc() map[string]string {
	return map_PackageRef
}

var map_PackageSpec = map[string]string{
	"":            "PackageSpec includes source/deploy archives and the reference of environment to build the package.",
	"environment": "Environment is a reference to the environment for building source archive.",
	"source":      "Source is the archive contains source code and dependencies file. If the package status is in PENDING state, builder manager will then notify builder to compile source and save the result as deployable archive.",
	"deployment":  "Deployment is the deployable archive that environment runtime used to run user function.",
	"buildcmd":    "BuildCommand is a custom build command that builder used to build the source archive.",
}

func (PackageSpec) SwaggerDoc() map[string]string {
	return map_PackageSpec
}

var map_PackageStatus = map[string]string{
	"":                    "PackageStatus contains the build status of a package also the build log for examination.",
	"buildstatus":         "BuildStatus is the package build status.",
	"buildlog":            "BuildLog stores build log during the compilation.",
	"contentHash":         "ContentHash fingerprints the package's INPUT content (RFC-0029 §3): the source archive when one is present, otherwise the deployment archive. A source package's deployment is the build's own product, so folding it in would make every successful build look like a fresh change and rebuild forever.\n\nIt is what makes a Git-applied Package converge without the CLI: buildermgr compares the spec's current hash against this one to decide whether the content actually changed, rather than relying on the CLI's status->pending poke.\n\nIt also covers packages that never build. A deploy-only or OCI package settles at BuildStatusNone, so the build-success path that re-stamps referencing Functions never runs for it — exactly the digest-pinned-OCI-in-Git golden path. Keying the re-stamp on this hash instead covers both shapes on one code path.\n\nAn EMPTY value means \"not yet recorded\" and must never read as \"changed\": every package has an empty hash on the first reconcile after this ships, and treating that as a change would rebuild the whole cluster at once. The reconciler seeds it without rebuilding.",
	"lastUpdateTimestamp": "LastUpdateTimestamp will store the timestamp the package was last updated metav1.Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. https://github.com/kubernetes/apimachinery/blob/44bd77c24ef93cd3a5eb6fef64e514025d10d44e/pkg/apis/meta/v1/time.go#L26-L35",
	"conditions":          "Conditions represent the latest observations of the package's state.",
}

func (PackageStatus) SwaggerDoc() map[string]string {
	return map_PackageStatus
}

var map_ProvisionedConcurrencyConfig = map[string]string{
	"":        "ProvisionedConcurrencyConfig opts this function into eager pre-warming of specialized pods (RFC-0026). Presence is the on switch: nil (the default) means the function uses the classic on-demand cold-start path. When non-nil, the executor's provisioner keeps at least Target specialized pods warm and published to the function's headless Service, exempt from the idle reaper. Additive and backward compatible.",
	"target":  "Target is the base number of warm specialized pods to maintain outside any schedule window. Must be >= 1. Schedule windows may override this (see Windows). Bounded by the namespace cap (executor.provisionedConcurrency.maxPerFunction, default 20).",
	"windows": "Windows is an optional list of schedule windows that override Target during specific time ranges (RFC-0026 PR 2). Empty in PR 1 — base Target is always in effect. Each window: a cron start expression, a duration, and a window-local target (0 means \"un-warm\" for the window's duration).",
}

func (ProvisionedConcurrencyConfig) SwaggerDoc() map[string]string {
	return map_ProvisionedConcurrencyConfig
}

var map_ProvisionedWindow = map[string]string{
	"":         "ProvisionedWindow describes a schedule window that overrides the base ProvisionedConcurrencyConfig.Target during a time range. The window is active from the cron-triggered start for Duration; while active, the effective target is the window's Target (overlapping windows take the max).",
	"name":     "Name identifies this window within the function's ProvisionedConcurrencyConfig.Windows list. Must be unique within the list (listMapKey=name).",
	"start":    "Start is a cron expression (5-field, robfig/cron, same parser as TimeTrigger) marking when each window instance opens. Prefix with \"CRON_TZ=<zone>\" (e.g. \"CRON_TZ=America/New_York 0 9 * * *\") to evaluate the schedule in a fixed timezone. Without a CRON_TZ prefix, the schedule is evaluated in the executor process's local timezone (UTC unless the deployment is configured otherwise) — this is intended behavior, not a default that may change; specify CRON_TZ explicitly if the window must not shift when the executor's local timezone changes.",
	"duration": "Duration is how long each window instance stays open. Format is Go time.ParseDuration (e.g. \"12h\", \"30m\"). Must be > 0.",
	"target":   "Target is the effective target while the window is open. 0 means \"un-warm\" — provisioned pods are drained for the window's duration.",
}

func (ProvisionedWindow) SwaggerDoc() map[string]string {
	return map_ProvisionedWindow
}

var map_RetryPolicy = map[string]string{
	"":            "RetryPolicy is the async delivery retry policy: the attempt budget and the exponential-backoff schedule between delivery attempts. All fields are optional; a nil field takes the platform default.",
	"maxAttempts": "MaxAttempts is the total number of delivery attempts before the invocation is dead-lettered. nil means DefaultMaxAttempts. Must be >= 1 when set.",
	"backoffBase": "BackoffBase is the delay before the first retry; it grows exponentially per attempt up to BackoffCap. nil means the platform default. Must be >= 0.",
	"backoffCap":  "BackoffCap bounds the per-retry backoff. nil means the platform default. Must be >= 0 and >= BackoffBase when both are set.",
	"jitter":      "Jitter, when non-nil and false, disables the randomized jitter the dispatcher otherwise adds to each backoff to avoid synchronized retries. nil means the platform default (jitter enabled).",
}

func (RetryPolicy) SwaggerDoc() map[string]string {
	return map_RetryPolicy
}

var map_RouteConfig = map[string]string{
	"":            "RouteConfig declares how the router exposes an HTTPTrigger through an external route provider. It is the provider-neutral successor to the deprecated CreateIngress + IngressConfig fields: the router routes it to the matching RouteProvider based on Provider.",
	"provider":    "Provider selects the route provider that reconciles this trigger's external route. \"ingress\" creates a networking.k8s.io Ingress (the deprecated path); \"gateway\" creates a gateway.networking.k8s.io HTTPRoute attached to an operator-managed Gateway. The \"gateway\" provider must be enabled on the router (GATEWAY_API_ENABLED).",
	"hostnames":   "Hostnames the route matches. For the gateway provider these become the HTTPRoute hostnames; for the ingress provider only the first is used as the Ingress rule host. Empty matches all hosts.",
	"path":        "Path is the request path the route matches (must be absolute, start with '/'). Defaults to \"/\" when empty.",
	"annotations": "Annotations are added to the generated route object (Ingress or HTTPRoute). Use these for implementation-specific configuration understood by your Ingress controller or Gateway implementation.",
	"tls":         "TLS names a Secret holding the TLS key and certificate. It applies to the ingress provider only; with the gateway provider TLS termination is configured on the Gateway listener and this field is ignored.",
	"gateway":     "Gateway holds Gateway-API-specific configuration. Required (at least one parentRef) when Provider is \"gateway\", unless the router is configured with a default Gateway parentRef.",
}

func (RouteConfig) SwaggerDoc() map[string]string {
	return map_RouteConfig
}

var map_RouterAuthToken = map[string]string{
	"": "RouterAuthToken defines the authorization token for accessing router",
}

func (RouterAuthToken) SwaggerDoc() map[string]string {
	return map_RouterAuthToken
}

var map_Runtime = map[string]string{
	"":          "Runtime is the setting for environment runtime. Bounded podspec / container safety rules — CEL admission gate for the simple, bounded fields. Per-container PodSpec.containers iteration stays in the webhook (ValidatePodSpecSafety / ValidateContainerSafety) because it exceeds the CEL cost budget. The has() guards are required because json:\"...,omitempty\" omits zero/empty values from the object.",
	"image":     "Image for containing the language runtime.",
	"container": "(Optional) Container allows the modification of the deployed runtime container using the Kubernetes Container spec. Fission overrides the following fields: - Name - Image; set to the Runtime.Image - TerminationMessagePath - ImagePullPolicy\n\nYou can set either PodSpec or Container, but not both. kubebuilder:validation:XPreserveUnknownFields=true",
	"podspec":   "(Optional) Podspec allows modification of deployed runtime pod with Kubernetes PodSpec The merging logic is briefly described below and detailed MergePodSpec function - Volumes mounts and env variables for function and fetcher container are appended - All additional containers and init containers are appended - Volume definitions are appended - Lists such as tolerations, ImagePullSecrets, HostAliases are appended - Structs are merged and variables from pod spec take precedence\n\nYou can set either PodSpec or Container, but not both.",
}

func (Runtime) SwaggerDoc() map[string]string {
	return map_Runtime
}

var map_SecretReference = map[string]string{
	"":          "SecretReference is a reference to a kubernetes secret.",
	"mountPath": "MountPath redirects this secret's file projection from the default /secrets/<namespace>/<name> to the given path, which is relative to the /secrets root (RFC-0030 §4): generic pool pods share a fixed volume set frozen at pool creation, so an arbitrary absolute path is not materializable there, and the container executor applies the same constraint for cross-executor consistency. Empty keeps today's <namespace>/<name> layout, so functions that do not set it are unaffected. No two secrets on one function may RESOLVE to the same directory (an explicit path colliding with another reference's default counts): the final segment written is the object's data key and keys are mutable after admission, so sharing a directory would let one object's later-added key collide with the other's file; the fetcher refuses such a write rather than truncating. Honoured on every executor: poolmgr and newdeploy via the fetcher, the container executor via a native projected volume. Not supported on an allowedFunctionsPerContainer:infinite environment, whose pods share one secrets tree across functions.",
}

func (SecretReference) SwaggerDoc() map[string]string {
	return map_SecretReference
}

var map_StateConfig = map[string]string{
	"":              "StateConfig declares a function's keyed-state keyspace and quotas (RFC-0023). Presence of the enclosing FunctionSpec.State is the on switch — there is no separate enabled flag, so the in-memory zero value and the stored object never disagree (the same rationale as StreamingConfig).",
	"keyspace":      "Keyspace names the durable keyspace this function reads and writes. Defaults to the function name; explicit so a function can be renamed without orphaning its data. The charset deliberately excludes ':' and '#' — ':' is a token-derivation info-string separator and '#' marks the platform-reserved \"<keyspace>#meta\" quota-accounting sibling.",
	"defaultTTL":    "DefaultTTL, when set, is applied to writes that carry no explicit TTL. Must be >= 0; zero (or nil) means keys do not expire by default.",
	"maxValueBytes": "MaxValueBytes caps a single value's size. 0 means the platform default (DefaultStateMaxValueBytes, 256KiB). Blobs belong in object storage.",
	"maxKeys":       "MaxKeys caps the number of live keys in the keyspace, enforced atomically with each write (quota.tla S3). 0 means the platform default (DefaultStateMaxKeys).",
	"backend":       "Backend selects a named statestore driver for this keyspace. Accepted and validated in v1 but not yet acted on: statesvc serves every keyspace from its single configured driver (per-function backend selection is a documented deferral).",
	"sticky":        "Sticky, when non-nil, opts the function into sticky routing: the router consistent-hashes the declared request key onto the ready-pod set so one key's requests land on one pod while the pod set is stable. Best-effort (an optimization, never a correctness dependency — S6): durable truth stays behind the state API.",
}

func (StateConfig) SwaggerDoc() map[string]string {
	return map_StateConfig
}

var map_StickyConfig = map[string]string{
	"":       "StickyConfig declares how the sticky routing key is extracted from a request. Requests missing the key fall back to the default endpoint pick.",
	"source": "Source is where to look for the key.",
	"name":   "Name is the header or query-parameter name holding the key, e.g. \"X-Session-Id\".",
}

func (StickyConfig) SwaggerDoc() map[string]string {
	return map_StickyConfig
}

var map_StreamingConfig = map[string]string{
	"":                   "StreamingConfig controls the router's streaming behavior for a function. Presence is the on switch: a non-nil Streaming enables the streaming path, nil (the default) is the classic buffered path. There is no separate enabled flag, so the in-memory zero value and the stored object never disagree.",
	"protocol":           "Protocol hints how the router proxies the response.",
	"idleTimeoutSeconds": "IdleTimeoutSeconds is the maximum time the router waits without bytes flowing from the function before it aborts the stream; reset on every chunk. 0 means use the package default (DefaultStreamIdleSeconds).",
	"maxDurationSeconds": "MaxDurationSeconds is an optional hard ceiling on total stream lifetime regardless of activity. 0 (the default) means no ceiling — the idle timeout governs. A streaming function does NOT inherit FunctionTimeout as a ceiling; that total-wall-clock cap is exactly what streaming escapes.",
}

func (StreamingConfig) SwaggerDoc() map[string]string {
	return map_StreamingConfig
}

var map_TimeTrigger = map[string]string{
	"": "TimeTrigger invokes functions based on given cron schedule.",
}

func (TimeTrigger) SwaggerDoc() map[string]string {
	return map_TimeTrigger
}

var map_TimeTriggerList = map[string]string{
	"": "TimeTriggerList is a list of TimeTriggers.",
}

func (TimeTriggerList) SwaggerDoc() map[string]string {
	return map_TimeTriggerList
}

var map_TimeTriggerSpec = map[string]string{
	"":            "TimeTriggerSpec invokes the specific function at a time or times specified by a cron string.",
	"cron":        "Cron schedule",
	"functionref": "The reference to function. Alias is read from the embedded FunctionReference.Alias (RFC-0025) — TimeTriggerSpec has no field of its own for it, so there is exactly one JSON path (spec.functionref.alias) and one Go path (spec.Alias, promoted) for the concept, never two competing ones. The timer publisher (a later RFC-0025 task) reads it the same way timer.go:80 already reads the promoted spec.Name today.",
	"method":      "HTTP Method for trigger, ex : GET, POST, PUT, DELETE, HEAD (default: \"POST\")",
	"subpath":     "Subpath to trigger a specific route if function internally supports routing, (default: \"/\")",
}

func (TimeTriggerSpec) SwaggerDoc() map[string]string {
	return map_TimeTriggerSpec
}

var map_TimeTriggerStatus = map[string]string{
	"": "TimeTriggerStatus describes the observed state of a TimeTrigger.",
}

func (TimeTriggerStatus) SwaggerDoc() map[string]string {
	return map_TimeTriggerStatus
}

var map_ToolConfig = map[string]string{
	"":            "ToolConfig declares how a Function is exposed as an MCP (Model Context Protocol) tool. The MCP server reuses the function's existing internal invocation path; this struct only declares the agent-facing tool contract. Presence of the enclosing FunctionSpec.Tool is the on switch — there is no separate enabled flag, so the in-memory zero value and the stored object never disagree (the same rationale as StreamingConfig).",
	"description": "Description is the human/agent-facing tool description surfaced in the MCP tools/list response. Required.",
	"inputSchema": "InputSchema is the JSON Schema (draft 2020-12) for the tool's arguments, surfaced verbatim as the MCP tool inputSchema. Stored as raw JSON so the CRD does not constrain the schema shape. When empty the tool advertises an open object schema ({\"type\":\"object\"}).",
	"toolName":    "ToolName overrides the advertised tool name. Defaults to \"<namespace>-<function name>\". Must match ^[a-zA-Z0-9_-]{1,64}$.",
	"alias":       "Alias, when set, targets a FunctionAlias by name (RFC-0025) instead of the live Function: the MCP registry serves the tool from the alias's currently-resolved FunctionVersion snapshot, and tools/call is proxied to the \":<alias>\" route rather than straight to the live Function. Empty (the default) preserves today's behavior. Router/registry-side resolution lands in a later RFC-0025 task — until then this field is accepted but inert.",
}

func (ToolConfig) SwaggerDoc() map[string]string {
	return map_ToolConfig
}

var map_TopicRef = map[string]string{
	"":                 "TopicRef is a message-queue topic destination for an async invocation result. Topics are namespace-scoped: the destination publishes to the source function's namespace (RFC-0024 rule R6).",
	"messageQueueType": "MessageQueueType selects the provider: \"statestore\" (the RFC-0027 built-in, no broker) now; broker types (e.g. kafka) with the egress phase.",
	"topic":            "Topic is the topic the result envelope is published to. The schema bounds mirror ValidateTopicName: a stream-safe charset excluding \"/\" so the topic/<namespace>/<topic> mapping cannot alias across namespaces.",
}

func (TopicRef) SwaggerDoc() map[string]string {
	return map_TopicRef
}

var map_VersioningConfig = map[string]string{
	"":       "VersioningConfig opts a Function into RFC-0025 immutable version snapshots and named aliases.",
	"mode":   "Mode auto (default) mints a version on every runtime-affecting update once the referenced package build succeeds; manual mints only on explicit `fission fn publish`.",
	"retain": "Retain bounds unaliased version history per function (GC floor 1). Defaults to 10. Alias-referenced versions are never GC'd.",
}

func (VersioningConfig) SwaggerDoc() map[string]string {
	return map_VersioningConfig
}

var map_Workflow = map[string]string{
	"": "Workflow declares a durable state machine whose task states are Fission functions (RFC-0022). The engine executes WorkflowRuns against a snapshot of this spec embedded in the run's event stream; editing a Workflow never changes in-flight runs.",
}

func (Workflow) SwaggerDoc() map[string]string {
	return map_Workflow
}

var map_WorkflowBranch = map[string]string{
	"":       "WorkflowBranch is one concurrent sub-machine of a Parallel state (or the iterator template of a Map state).",
	"states": "MaxProperties=20 (vs 100 top-level) keeps the apiserver's CEL cost estimate for doubly-nested rules under budget — the phase-1 lesson.",
}

func (WorkflowBranch) SwaggerDoc() map[string]string {
	return map_WorkflowBranch
}

var map_WorkflowBranchState = map[string]string{
	"": "WorkflowBranchState is WorkflowState minus the fan-out fields: nested Parallel/Map is impossible BY TYPE, which is what keeps the CRD schema non-recursive (controller-gen cannot render a self-referential type).",
}

func (WorkflowBranchState) SwaggerDoc() map[string]string {
	return map_WorkflowBranchState
}

var map_WorkflowCatchRoute = map[string]string{
	"":           "WorkflowCatchRoute routes a matched error class to a next state.",
	"errorType":  "ErrorType matches a typed function error ({\"errorType\": ...} body), a built-in class (Fission.PermanentError, Fission.FunctionError, Fission.Timeout), or Fission.All (matches anything).",
	"resultPath": "ResultPath, when set, merges the error object ({\"errorType\": ..., \"cause\": ...}) into the flowing document at this JSONPath, so the catch target still sees the business data (e.g. retry a charge after a grace period). Unset keeps the Step-Functions-parity default: the error object REPLACES the document.",
}

func (WorkflowCatchRoute) SwaggerDoc() map[string]string {
	return map_WorkflowCatchRoute
}

var map_WorkflowChoiceCondition = map[string]string{
	"":         "WorkflowChoiceCondition is a leaf comparison against the state input. Exactly one operator must be set. Numeric values use resource.Quantity (CRDs cannot carry floats; Quantity accepts YAML numbers and strings).",
	"variable": "Variable is a JSONPath into the state's (shaped) input. Required on every leaf condition — enforced by the webhook, not the schema: this struct is inline-embedded in WorkflowChoiceRule, and a schema-required field would wrongly reject composite (and/or/not) rules that carry no inline leaf.",
}

func (WorkflowChoiceCondition) SwaggerDoc() map[string]string {
	return map_WorkflowChoiceCondition
}

var map_WorkflowChoiceRule = map[string]string{
	"":     "WorkflowChoiceRule is one ordered rule of a Choice state: either a leaf condition (inline) or exactly one of And/Or/Not over leaf conditions (depth-1 composition; deeper nesting is additive later).",
	"next": "Next names the state to transition to when this rule matches.",
}

func (WorkflowChoiceRule) SwaggerDoc() map[string]string {
	return map_WorkflowChoiceRule
}

var map_WorkflowList = map[string]string{
	"": "WorkflowList is a list of Workflows.",
}

func (WorkflowList) SwaggerDoc() map[string]string {
	return map_WorkflowList
}

var map_WorkflowRetentionPolicy = map[string]string{
	"": "WorkflowRetentionPolicy bounds retained history for finished runs.",
}

func (WorkflowRetentionPolicy) SwaggerDoc() map[string]string {
	return map_WorkflowRetentionPolicy
}

var map_WorkflowRun = map[string]string{
	"": "WorkflowRun is one execution of a Workflow. Full step history lives in the statestore EventLog stream for the run, never in etcd; status carries a bounded tail for kubectl visibility.",
}

func (WorkflowRun) SwaggerDoc() map[string]string {
	return map_WorkflowRun
}

var map_WorkflowRunEventSummary = map[string]string{
	"": "WorkflowRunEventSummary is one bounded-tail history entry for kubectl visibility; the full history lives in the statestore EventLog.",
}

func (WorkflowRunEventSummary) SwaggerDoc() map[string]string {
	return map_WorkflowRunEventSummary
}

var map_WorkflowRunList = map[string]string{
	"": "WorkflowRunList is a list of WorkflowRuns.",
}

func (WorkflowRunList) SwaggerDoc() map[string]string {
	return map_WorkflowRunList
}

var map_WorkflowRunSpec = map[string]string{
	"":                   "WorkflowRunSpec identifies the Workflow to execute and the run's input.",
	"workflowRef":        "WorkflowRef names the Workflow (same namespace) this run executes.",
	"workflowGeneration": "WorkflowGeneration records (for observability) which Workflow generation this run executes. It is NOT the pinning mechanism: the authoritative spec is the snapshot the engine embeds in the run's event stream at RunStarted; a Workflow edit or deletion mid-run can neither fork nor strand a run. Set by the CLI; 0 means unknown.",
	"input":              "Input is the run's initial input document — ANY JSON value (apiextensionsv1.JSON, not RawExtension: the RawExtension schema is type=object and the apiserver would reject a bare string/array/ number). Webhook-capped at 256KiB (etcd objects cap at ~1.5MiB) — pass larger inputs by reference.",
}

func (WorkflowRunSpec) SwaggerDoc() map[string]string {
	return map_WorkflowRunSpec
}

var map_WorkflowRunStatus = map[string]string{
	"":             "WorkflowRunStatus describes the observed state of a WorkflowRun.",
	"activeStates": "ActiveStates lists the state names currently executing.",
	"output":       "Output holds the final output inline up to the step-I/O spill threshold — ANY JSON value (see Input for why apiextensionsv1.JSON); larger outputs spill to the statestore KV and OutputRef points there (the CLI dereferences).",
	"errorType":    "ErrorType and Cause carry the terminal failure classification so kubectl answers \"why did it fail\" without the history endpoint. Cause is bounded; the full detail lives in the run history.",
	"recentEvents": "RecentEvents is a bounded (<=20) tail; full history is in the EventLog.",
}

func (WorkflowRunStatus) SwaggerDoc() map[string]string {
	return map_WorkflowRunStatus
}

var map_WorkflowSpec = map[string]string{
	"":                 "WorkflowSpec is a state machine: states are data, logic lives in functions.",
	"startAt":          "StartAt names the state execution begins at.",
	"states":           "States is the state machine graph, keyed by state name. The size bound mirrors validation.MaxWorkflowStates and lets the apiserver's CEL cost estimator bound rules on nested types.",
	"defaultRetry":     "DefaultRetry applies to Task states that do not set their own Retry.",
	"timeout":          "Timeout bounds a whole run; expiry fails it with errorType Fission.Timeout. Defaults to 24h (a mis-authored graph or endlessly caught-and-retried loop must not hold an active run forever).",
	"historyRetention": "HistoryRetention bounds stored history (count + age) per finished run.",
}

func (WorkflowSpec) SwaggerDoc() map[string]string {
	return map_WorkflowSpec
}

var map_WorkflowState = map[string]string{
	"":               "WorkflowState is one state in the machine. Exactly the fields for its Type may be set (enforced at admission).",
	"function":       "Function is the Task state's target.",
	"timeout":        "Timeout bounds one attempt of a Task invocation.",
	"retry":          "Retry overrides the workflow's DefaultRetry for this Task.",
	"catch":          "Catch routes a failed Task (retries exhausted, or a permanent error) to another state by matched errorType; first match wins.",
	"choices":        "Choices are the Choice state's ordered rules; first match wins.",
	"default":        "Default names the state a Choice falls through to when no rule matches; without it, no-match fails the run (Fission.NoChoiceMatched).",
	"branches":       "Branches are the Parallel state's concurrent sub-machines (or the Map state's single iterator template). Branch states cannot nest further fan-out — enforced by the bounded WorkflowBranchState type.",
	"itemsPath":      "ItemsPath selects the array a Map state iterates (one branch per element, input = the element).",
	"duration":       "Duration is how long a Wait state pauses the run — durably: the delay is a statestore Queue message, so a controller restart never loses it (robfig/cron-style absolute schedules stay with the timer subsystem; only durations here).",
	"maxConcurrency": "MaxConcurrency throttles how many branches execute at once. Zero means the engine default (10) — NOT unbounded: an unthrottled large Map against poolmgr is a self-inflicted cold-start burst. The default is applied by the engine, not the schema: a schema default would stamp the field onto every state type.",
	"inputPath":      "InputPath/ResultPath/OutputPath shape step I/O with JSONPath (Step Functions semantics; dialect pinned in pkg/workflow/expr).",
	"next":           "Next names the state to run after this one; exactly one of Next/End is set on Task states (Succeed/Fail are implicitly terminal).",
}

func (WorkflowState) SwaggerDoc() map[string]string {
	return map_WorkflowState
}

var map_WorkflowStatus = map[string]string{
	"": "WorkflowStatus describes the observed state of a Workflow.",
}

func (WorkflowStatus) SwaggerDoc() map[string]string {
	return map_WorkflowStatus
}

// AUTO-GENERATED FUNCTIONS END HERE
