{{- if dig "enabled" false .Values.workflows }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-workflow
  namespace: {{ .Release.Namespace }}
  {{- include "fission.saAnnotationsBlock" (dict "root" . "component" "workflow") }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: workflow
    application: fission-workflow
    {{- with include "fission.saLabels" (dict "root" . "component" "workflow") }}{{ . | nindent 4 }}{{- end }}
{{- end }}
