{{- if dig "enabled" false .Values.workflows }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-workflow
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: workflow
    application: fission-workflow
{{- end }}
