FROM alpine:3.5

WORKDIR /app

RUN apk add --no-cache python python-dev build-base py-pip libev-dev libffi-dev && \
    pip install --upgrade pip && \
    rm -r /root/.cache

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app

ENTRYPOINT ["python"]
CMD ["server.py"]
