/*
Copyright The Fission Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/fission/fission/pkg/apis/core/v1"
	scheme "github.com/fission/fission/pkg/apis/genclient/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CanaryConfigsGetter has a method to return a CanaryConfigInterface.
// A group's client should implement this interface.
type CanaryConfigsGetter interface {
	CanaryConfigs(namespace string) CanaryConfigInterface
}

// CanaryConfigInterface has methods to work with CanaryConfig resources.
type CanaryConfigInterface interface {
	Create(*v1.CanaryConfig) (*v1.CanaryConfig, error)
	Update(*v1.CanaryConfig) (*v1.CanaryConfig, error)
	UpdateStatus(*v1.CanaryConfig) (*v1.CanaryConfig, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CanaryConfig, error)
	List(opts metav1.ListOptions) (*v1.CanaryConfigList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CanaryConfig, err error)
	CanaryConfigExpansion
}

// canaryConfigs implements CanaryConfigInterface
type canaryConfigs struct {
	client rest.Interface
	ns     string
}

// newCanaryConfigs returns a CanaryConfigs
func newCanaryConfigs(c *CoreV1Client, namespace string) *canaryConfigs {
	return &canaryConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the _canaryConfig, and returns the corresponding canaryConfig object, and an error if there is any.
func (c *canaryConfigs) Get(name string, options metav1.GetOptions) (result *v1.CanaryConfig, err error) {
	result = &v1.CanaryConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("canaryconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.Background()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CanaryConfigs that match those selectors.
func (c *canaryConfigs) List(opts metav1.ListOptions) (result *v1.CanaryConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CanaryConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("canaryconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(context.Background()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested canaryConfigs.
func (c *canaryConfigs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("canaryconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(context.Background())
}

// Create takes the representation of a _canaryConfig and creates it.  Returns the server's representation of the canaryConfig, and an error, if there is any.
func (c *canaryConfigs) Create(_canaryConfig *v1.CanaryConfig) (result *v1.CanaryConfig, err error) {
	result = &v1.CanaryConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("canaryconfigs").
		Body(_canaryConfig).
		Do(context.Background()).
		Into(result)
	return
}

// Update takes the representation of a _canaryConfig and updates it. Returns the server's representation of the canaryConfig, and an error, if there is any.
func (c *canaryConfigs) Update(_canaryConfig *v1.CanaryConfig) (result *v1.CanaryConfig, err error) {
	result = &v1.CanaryConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("canaryconfigs").
		Name(_canaryConfig.Name).
		Body(_canaryConfig).
		Do(context.Background()).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *canaryConfigs) UpdateStatus(_canaryConfig *v1.CanaryConfig) (result *v1.CanaryConfig, err error) {
	result = &v1.CanaryConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("canaryconfigs").
		Name(_canaryConfig.Name).
		SubResource("status").
		Body(_canaryConfig).
		Do(context.Background()).
		Into(result)
	return
}

// Delete takes name of the _canaryConfig and deletes it. Returns an error if one occurs.
func (c *canaryConfigs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("canaryconfigs").
		Name(name).
		Body(options).
		Do(context.Background()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *canaryConfigs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("canaryconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do(context.Background()).
		Error()
}

// Patch applies the patch and returns the patched canaryConfig.
func (c *canaryConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CanaryConfig, err error) {
	result = &v1.CanaryConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("canaryconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.Background()).
		Into(result)
	return
}
