/*
Copyright The Fission Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/fission/fission/pkg/apis/core/v1"
	scheme "github.com/fission/fission/pkg/apis/genclient/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MessageQueueTriggersGetter has a method to return a MessageQueueTriggerInterface.
// A group's client should implement this interface.
type MessageQueueTriggersGetter interface {
	MessageQueueTriggers(namespace string) MessageQueueTriggerInterface
}

// MessageQueueTriggerInterface has methods to work with MessageQueueTrigger resources.
type MessageQueueTriggerInterface interface {
	Create(*v1.MessageQueueTrigger) (*v1.MessageQueueTrigger, error)
	Update(*v1.MessageQueueTrigger) (*v1.MessageQueueTrigger, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.MessageQueueTrigger, error)
	List(opts metav1.ListOptions) (*v1.MessageQueueTriggerList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MessageQueueTrigger, err error)
	MessageQueueTriggerExpansion
}

// messageQueueTriggers implements MessageQueueTriggerInterface
type messageQueueTriggers struct {
	client rest.Interface
	ns     string
}

// newMessageQueueTriggers returns a MessageQueueTriggers
func newMessageQueueTriggers(c *CoreV1Client, namespace string) *messageQueueTriggers {
	return &messageQueueTriggers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the _messageQueueTrigger, and returns the corresponding messageQueueTrigger object, and an error if there is any.
func (c *messageQueueTriggers) Get(name string, options metav1.GetOptions) (result *v1.MessageQueueTrigger, err error) {
	result = &v1.MessageQueueTrigger{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.Background()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MessageQueueTriggers that match those selectors.
func (c *messageQueueTriggers) List(opts metav1.ListOptions) (result *v1.MessageQueueTriggerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MessageQueueTriggerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(context.Background()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested messageQueueTriggers.
func (c *messageQueueTriggers) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(context.Background())
}

// Create takes the representation of a _messageQueueTrigger and creates it.  Returns the server's representation of the messageQueueTrigger, and an error, if there is any.
func (c *messageQueueTriggers) Create(_messageQueueTrigger *v1.MessageQueueTrigger) (result *v1.MessageQueueTrigger, err error) {
	result = &v1.MessageQueueTrigger{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		Body(_messageQueueTrigger).
		Do(context.Background()).
		Into(result)
	return
}

// Update takes the representation of a _messageQueueTrigger and updates it. Returns the server's representation of the messageQueueTrigger, and an error, if there is any.
func (c *messageQueueTriggers) Update(_messageQueueTrigger *v1.MessageQueueTrigger) (result *v1.MessageQueueTrigger, err error) {
	result = &v1.MessageQueueTrigger{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		Name(_messageQueueTrigger.Name).
		Body(_messageQueueTrigger).
		Do(context.Background()).
		Into(result)
	return
}

// Delete takes name of the _messageQueueTrigger and deletes it. Returns an error if one occurs.
func (c *messageQueueTriggers) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		Name(name).
		Body(options).
		Do(context.Background()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *messageQueueTriggers) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do(context.Background()).
		Error()
}

// Patch applies the patch and returns the patched messageQueueTrigger.
func (c *messageQueueTriggers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MessageQueueTrigger, err error) {
	result = &v1.MessageQueueTrigger{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("messagequeuetriggers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.Background()).
		Into(result)
	return
}
