/*
Copyright The Fission Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/fission/fission/pkg/apis/core/v1"
	scheme "github.com/fission/fission/pkg/apis/genclient/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PackagesGetter has a method to return a PackageInterface.
// A group's client should implement this interface.
type PackagesGetter interface {
	Packages(namespace string) PackageInterface
}

// PackageInterface has methods to work with Package resources.
type PackageInterface interface {
	Create(*v1.Package) (*v1.Package, error)
	Update(*v1.Package) (*v1.Package, error)
	UpdateStatus(*v1.Package) (*v1.Package, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Package, error)
	List(opts metav1.ListOptions) (*v1.PackageList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Package, err error)
	PackageExpansion
}

// packages implements PackageInterface
type packages struct {
	client rest.Interface
	ns     string
}

// newPackages returns a Packages
func newPackages(c *CoreV1Client, namespace string) *packages {
	return &packages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the _package, and returns the corresponding package object, and an error if there is any.
func (c *packages) Get(name string, options metav1.GetOptions) (result *v1.Package, err error) {
	result = &v1.Package{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.Background()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Packages that match those selectors.
func (c *packages) List(opts metav1.ListOptions) (result *v1.PackageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PackageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(context.Background()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested packages.
func (c *packages) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("packages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(context.Background())
}

// Create takes the representation of a _package and creates it.  Returns the server's representation of the package, and an error, if there is any.
func (c *packages) Create(_package *v1.Package) (result *v1.Package, err error) {
	result = &v1.Package{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("packages").
		Body(_package).
		Do(context.Background()).
		Into(result)
	return
}

// Update takes the representation of a _package and updates it. Returns the server's representation of the package, and an error, if there is any.
func (c *packages) Update(_package *v1.Package) (result *v1.Package, err error) {
	result = &v1.Package{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("packages").
		Name(_package.Name).
		Body(_package).
		Do(context.Background()).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *packages) UpdateStatus(_package *v1.Package) (result *v1.Package, err error) {
	result = &v1.Package{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("packages").
		Name(_package.Name).
		SubResource("status").
		Body(_package).
		Do(context.Background()).
		Into(result)
	return
}

// Delete takes name of the _package and deletes it. Returns an error if one occurs.
func (c *packages) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packages").
		Name(name).
		Body(options).
		Do(context.Background()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *packages) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packages").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do(context.Background()).
		Error()
}

// Patch applies the patch and returns the patched package.
func (c *packages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Package, err error) {
	result = &v1.Package{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("packages").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.Background()).
		Into(result)
	return
}
