ARG GO_VERSION=1.12.7

FROM ubuntu:18.04 AS base
WORKDIR /
RUN apt update && apt install -y ca-certificates && rm -rf /var/lib/apt/lists/*

FROM golang:${GO_VERSION} AS builder

ENV GOPATH /usr
ENV APP	   ${GOPATH}/src/github.com/fission/fission/environments/go

WORKDIR ${APP}

ADD context	    ${APP}/context
ADD server.go   ${APP}

RUN go get
RUN go build -a -o /server server.go

FROM base
COPY --from=builder /server /

ENTRYPOINT ["/server"]
EXPOSE 8888
