apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- fission.io_canaryconfigs.yaml
- fission.io_environments.yaml
- fission.io_fissiontenants.yaml
- fission.io_functionaliases.yaml
- fission.io_functions.yaml
- fission.io_functionversions.yaml
- fission.io_httptriggers.yaml
- fission.io_kuberneteswatchtriggers.yaml
- fission.io_messagequeuetriggers.yaml
- fission.io_packages.yaml
- fission.io_timetriggers.yaml
- fission.io_workflowruns.yaml
- fission.io_workflows.yaml
labels:
- includeSelectors: true
  pairs:
    group: fission.io
