{{- if include "fission.tenancyControllerEnabled" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-tenant-controller
  namespace: {{ .Release.Namespace }}
  {{- include "fission.saAnnotationsBlock" (dict "root" . "component" "tenantController") }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: tenantcontroller
    {{- with include "fission.saLabels" (dict "root" . "component" "tenantController") }}{{ . | nindent 4 }}{{- end }}
{{- end }}
