{{- if include "fission.tenancyControllerEnabled" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-tenant-controller
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: tenantcontroller
{{- end }}
