{{- if and .Values.statestore.enabled (eq .Values.statestore.mode "embedded") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-statestore
  labels:
    svc: statestore
    application: fission-statestore
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- end }}
