{{- if and .Values.statestore.enabled (eq .Values.statestore.mode "embedded") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-statestore
  namespace: {{ .Release.Namespace }}
  {{- include "fission.saAnnotationsBlock" (dict "root" . "component" "statestore") }}
  labels:
    svc: statestore
    application: fission-statestore
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- with include "fission.saLabels" (dict "root" . "component" "statestore") }}{{ . | nindent 4 }}{{- end }}
{{- end }}
