/*
Copyright 2026 The Fission Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// buildkit-build is the per-package builder invoked by Fission's
// buildermgr (RFC-0001 Phase 4) when an Environment opts into the
// BuildKit-flavored builder. It is a small shim around `buildctl build`
// that:
//
//  1. Reads the build context, target image ref, and base image from
//     environment variables (BUILDKIT_CONTEXT / BUILDKIT_IMAGE_REF /
//     BUILDKIT_BASE_IMAGE) — the same wire contract documented in
//     pkg/builder/oci.go.
//  2. Materializes a minimal Dockerfile that COPYs the source on top
//     of the base runtime image at /userfunc — the path Fission
//     environments already expect.
//  3. Invokes buildctl with --metadata-file so the produced image's
//     digest is captured deterministically.
//  4. Emits "manifest-digest: sha256:..." on stdout — the marker the
//     fission builder pod's OCIHandler scans for when constructing the
//     OCIBuildResponse.
//
// Errors are written to stderr with the buildctl logs prepended so the
// builder pod can ferry them back into Package.Status.BuildLog.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	envContext    = "BUILDKIT_CONTEXT"
	envImageRef   = "BUILDKIT_IMAGE_REF"
	envBaseImage  = "BUILDKIT_BASE_IMAGE"
	envBuildKitd  = "BUILDKITD_ADDRESS"
	envExtraArgs  = "BUILDKIT_EXTRA_ARGS"
	digestPrefix  = "manifest-digest:"
	defaultBuildd = "tcp://127.0.0.1:1234"
)

func main() {
	if err := run(os.Args, os.Getenv, os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, "buildkit-build:", err)
		os.Exit(1)
	}
}

// envFn is a small indirection so tests can inject a deterministic
// environment without leaning on os.Setenv (which is global).
type envFn func(string) string

// run is the testable core: every dependency on the OS is threaded
// through arguments. Splitting main from run lets us cover the happy
// path, missing-env, and digest-emission cases without spawning real
// buildctl processes.
func run(_ []string, getenv envFn, stdout, stderr io.Writer) error {
	contextDir := getenv(envContext)
	imageRef := getenv(envImageRef)
	baseImage := getenv(envBaseImage)
	if contextDir == "" || imageRef == "" || baseImage == "" {
		return fmt.Errorf("required env vars %s, %s, %s must all be set",
			envContext, envImageRef, envBaseImage)
	}
	if _, err := os.Stat(contextDir); err != nil {
		return fmt.Errorf("context %q is not accessible: %w", contextDir, err)
	}

	dockerfileDir, err := os.MkdirTemp("", "fission-buildkit-")
	if err != nil {
		return fmt.Errorf("could not create dockerfile dir: %w", err)
	}
	// Best-effort cleanup; build pods are short-lived so this is mostly
	// for the unit-test harness.
	defer os.RemoveAll(dockerfileDir)

	if err := writeDockerfile(dockerfileDir, baseImage); err != nil {
		return err
	}

	metadataFile := filepath.Join(dockerfileDir, "metadata.json")

	args := buildctlArgs(contextDir, dockerfileDir, imageRef, metadataFile)
	cmd := exec.Command("buildctl", args...)
	cmd.Stderr = stderr
	cmd.Stdout = stderr // buildctl logs to stderr; merge into the same stream
	if addr := getenv(envBuildKitd); addr != "" {
		cmd.Env = append(os.Environ(), "BUILDKIT_HOST="+addr)
	} else {
		cmd.Env = append(os.Environ(), "BUILDKIT_HOST="+defaultBuildd)
	}

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("buildctl build failed: %w", err)
	}

	digest, err := readDigest(metadataFile)
	if err != nil {
		return err
	}
	fmt.Fprintf(stdout, "%s %s\n", digestPrefix, digest)
	return nil
}

// writeDockerfile emits the minimal build recipe used by the
// BuildKit-flavored builder: layer the user's source on top of the base
// runtime image at /userfunc. We deliberately keep this hand-rolled
// rather than letting users provide a Dockerfile — the contract with
// the Fission runtime depends on this layout, and a user-provided
// Dockerfile could break that.
func writeDockerfile(dir, baseImage string) error {
	df := fmt.Sprintf(`# Generated by buildkit-build
FROM %s
COPY . /userfunc/
`, baseImage)
	return os.WriteFile(filepath.Join(dir, "Dockerfile"), []byte(df), 0o600)
}

// buildctlArgs assembles the buildctl invocation. Kept as a pure
// function so the test suite can pin the exact argument layout — that
// matters because buildctl's CLI surface evolves and a regression here
// would break every BuildKit-flavored build silently.
func buildctlArgs(contextDir, dockerfileDir, imageRef, metadataFile string) []string {
	args := []string{
		"build",
		"--frontend", "dockerfile.v0",
		"--local", "context=" + contextDir,
		"--local", "dockerfile=" + dockerfileDir,
		"--output", "type=image,name=" + imageRef + ",push=true",
		"--metadata-file", metadataFile,
	}
	if extra := os.Getenv(envExtraArgs); extra != "" {
		// Allow operators to slip in flags like --opt registry.insecure=true
		// without recompiling the binary.
		args = append(args, strings.Fields(extra)...)
	}
	return args
}

// readDigest pulls the manifest digest out of buildctl's --metadata-file
// JSON. The schema is a flat map; we accept either of the two keys
// buildctl emits across its currently supported versions
// ("containerimage.digest" and "image.name") — the digest field is the
// stable one we care about, but we keep the fallback in case operators
// pin older buildctl versions.
func readDigest(metadataPath string) (string, error) {
	raw, err := os.ReadFile(metadataPath)
	if err != nil {
		return "", fmt.Errorf("could not read metadata file %q: %w", metadataPath, err)
	}
	var meta map[string]any
	if err := json.Unmarshal(raw, &meta); err != nil {
		return "", fmt.Errorf("invalid metadata json: %w", err)
	}
	for _, k := range []string{"containerimage.digest", "image.digest"} {
		if v, ok := meta[k].(string); ok && v != "" {
			return v, nil
		}
	}
	return "", errors.New("metadata file did not contain a manifest digest")
}
