/*
Copyright The Fission Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// CanaryConfigListerExpansion allows custom methods to be added to
// CanaryConfigLister.
type CanaryConfigListerExpansion interface{}

// CanaryConfigNamespaceListerExpansion allows custom methods to be added to
// CanaryConfigNamespaceLister.
type CanaryConfigNamespaceListerExpansion interface{}

// EnvironmentListerExpansion allows custom methods to be added to
// EnvironmentLister.
type EnvironmentListerExpansion interface{}

// EnvironmentNamespaceListerExpansion allows custom methods to be added to
// EnvironmentNamespaceLister.
type EnvironmentNamespaceListerExpansion interface{}

// FunctionListerExpansion allows custom methods to be added to
// FunctionLister.
type FunctionListerExpansion interface{}

// FunctionNamespaceListerExpansion allows custom methods to be added to
// FunctionNamespaceLister.
type FunctionNamespaceListerExpansion interface{}

// HTTPTriggerListerExpansion allows custom methods to be added to
// HTTPTriggerLister.
type HTTPTriggerListerExpansion interface{}

// HTTPTriggerNamespaceListerExpansion allows custom methods to be added to
// HTTPTriggerNamespaceLister.
type HTTPTriggerNamespaceListerExpansion interface{}

// KubernetesWatchTriggerListerExpansion allows custom methods to be added to
// KubernetesWatchTriggerLister.
type KubernetesWatchTriggerListerExpansion interface{}

// KubernetesWatchTriggerNamespaceListerExpansion allows custom methods to be added to
// KubernetesWatchTriggerNamespaceLister.
type KubernetesWatchTriggerNamespaceListerExpansion interface{}

// MessageQueueTriggerListerExpansion allows custom methods to be added to
// MessageQueueTriggerLister.
type MessageQueueTriggerListerExpansion interface{}

// MessageQueueTriggerNamespaceListerExpansion allows custom methods to be added to
// MessageQueueTriggerNamespaceLister.
type MessageQueueTriggerNamespaceListerExpansion interface{}

// PackageListerExpansion allows custom methods to be added to
// PackageLister.
type PackageListerExpansion interface{}

// PackageNamespaceListerExpansion allows custom methods to be added to
// PackageNamespaceLister.
type PackageNamespaceListerExpansion interface{}

// TimeTriggerListerExpansion allows custom methods to be added to
// TimeTriggerLister.
type TimeTriggerListerExpansion interface{}

// TimeTriggerNamespaceListerExpansion allows custom methods to be added to
// TimeTriggerNamespaceLister.
type TimeTriggerNamespaceListerExpansion interface{}
