# A docker image for the func container.

# default variant is the official alpine node image (much smaller than the standard image)
FROM node:8-alpine

ADD server.js /usr/src/app/server.js

EXPOSE 8888
