# A docker image for the func container.

# debian variant is the official standard node image (larger than the alpine image)
FROM node:8

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY package.json /usr/src/app/
RUN npm install && npm cache clean --force
COPY . /usr/src/app

# ADD server.js /usr/src/app/server.js

EXPOSE 8888
