// SPDX-FileCopyrightText: The Fission Authors
//
// SPDX-License-Identifier: Apache-2.0

package workflow

import (
	"encoding/json"
	"encoding/json/jsontext"
	jsonv2 "encoding/json/v2"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	fv1 "github.com/fission/fission/pkg/apis/core/v1"
	"github.com/fission/fission/pkg/statestore"
)

// This file is a compat gate ahead of an encoding/json -> encoding/json/v2
// migration of pkg/workflow's durable JSON: checkpoint docs (spill.go),
// event payloads (events.go), and the lenient error-classifying probe
// (invoker.go). The fixtures below are canned byte literals representing
// what today's encoding/json (v1) actually produces and actually accepts.
// They are not aspirational: every literal in this file was generated by
// running the real v1 marshal/decode paths on this machine (go1.27.0) and
// copied in, then cross-checked against the real code below.
//
// One more divergence surfaced while building these fixtures, not covered
// by a dedicated test here but worth carrying into the migration: v2's
// "omitempty" only omits a value that would encode as JSON null, "", {}, or
// [] — unlike v1, it does NOT omit a zero number or false bool. A v1
// `json:"attempt,omitempty"` int32 field (Event.Attempt, WorkflowState.
// MaxConcurrency, etc.) stops being omitted at zero under v2 defaults
// unless retagged "omitzero". That changes wire bytes (not just decode
// strictness) for every existing "omitempty" numeric/bool field.

// wantCheckpointState is the fully-populated RunState used by
// TestCheckpointDocCompat_V1RoundTrip. Field choices: Terminal=Failed so
// both the success (Results["task1/1"]) and failure (Results["task2/1"],
// ErrorType, Cause) shapes are exercised in one fixture; BranchRuns/RegionID
// are left zero (parallel-region checkpointing is a distinct, separately
// spillable shape, not part of this linear-run wire contract).
func wantCheckpointState() *RunState {
	spec := &fv1.WorkflowSpec{
		StartAt: "task1",
		States: map[string]fv1.WorkflowState{
			"task1": {
				Type:     fv1.WorkflowStateTask,
				Function: &fv1.FunctionReference{Type: fv1.FunctionReferenceTypeFunctionName, Name: "greeter"},
				Next:     "task2",
			},
			"task2": {
				Type:     fv1.WorkflowStateTask,
				Function: &fv1.FunctionReference{Type: fv1.FunctionReferenceTypeFunctionName, Name: "finisher"},
				End:      true,
			},
		},
	}
	return &RunState{
		Spec:    spec,
		Input:   json.RawMessage(`{"greeting":"hi"}`),
		Current: "task2",
		Doc:     json.RawMessage(`{"greeting":"hi","step1":"done"}`),
		Attempts: map[string]int32{
			"task1": 1,
			"task2": 2,
		},
		Results: map[string]stepResult{
			"task1/1": {Succeeded: true},
			"task2/1": {Succeeded: false, ErrorType: "Fission.FunctionError", Cause: json.RawMessage(`"boom"`)},
		},
		TimersFired: map[string]bool{
			"task2/1": true,
		},
		Terminal:  fv1.WorkflowRunFailed,
		ErrorType: "Fission.FunctionError",
		Cause:     json.RawMessage(`"boom"`),
		StartedAt: time.Date(2026, 8, 20, 12, 0, 0, 0, time.UTC),
		LastSeq:   5,
		Recent: []fv1.WorkflowRunEventSummary{
			{Seq: 1, Type: "RunStarted", At: metav1.NewTime(time.Date(2026, 8, 20, 12, 0, 0, 0, time.UTC))},
			{Seq: 5, Type: "RunFailed", At: metav1.NewTime(time.Date(2026, 8, 20, 12, 0, 5, 0, time.UTC)), Note: "boom"},
		},
	}
}

const wantCheckpointUID = "11111111-2222-3333-4444-555555555555"

// checkpointJSONv1 is the exact byte sequence json.Marshal(checkpointDoc{...})
// produces TODAY for wantCheckpointState (verified below, not just asserted).
// Notably fv1.FunctionReference.FunctionWeights has no `omitempty` tag, so
// "functionweights":null rides along on every function reference — a real
// wire-shape detail a hand-typed fixture would otherwise miss.
//
// compat gate for the json/v2 migration — old durable bytes must keep
// decoding; if this fails after a migration commit, add compat options at
// the decode site, do not update the fixture. (The marshal-equality half of
// this test, above, is a weaker canary that legitimately fires on additive
// schema changes to fv1 types — e.g. a new non-omitempty field. Only the
// decode half is the hard gate; do not weaken it to silence the canary.)
const checkpointJSONv1 = `{"uid":"11111111-2222-3333-4444-555555555555","state":{"spec":{"startAt":"task1","states":{"task1":{"type":"Task","function":{"type":"name","name":"greeter","functionweights":null},"next":"task2"},"task2":{"type":"Task","function":{"type":"name","name":"finisher","functionweights":null},"end":true}}},"input":{"greeting":"hi"},"current":"task2","doc":{"greeting":"hi","step1":"done"},"attempts":{"task1":1,"task2":2},"results":{"task1/1":{"succeeded":true},"task2/1":{"succeeded":false,"errorType":"Fission.FunctionError","cause":"boom"}},"timersFired":{"task2/1":true},"terminal":"Failed","errorType":"Fission.FunctionError","cause":"boom","startedAt":"2026-08-20T12:00:00Z","lastSeq":5,"recent":[{"seq":1,"type":"RunStarted","at":"2026-08-20T12:00:00Z"},{"seq":5,"type":"RunFailed","at":"2026-08-20T12:00:05Z","note":"boom"}]}}`

func TestCheckpointDocCompat_V1RoundTrip(t *testing.T) {
	t.Parallel()

	// 1. The literal really is what v1 produces today (byte-identical, not
	// just JSON-equivalent: map keys sort deterministically so this is
	// reproducible).
	got, err := json.Marshal(checkpointDoc{UID: wantCheckpointUID, State: wantCheckpointState()})
	require.NoError(t, err)
	require.JSONEq(t, checkpointJSONv1, string(got))
	assert.Equal(t, checkpointJSONv1, string(got), "byte-identical, not just semantically equal")

	// 2. The literal still decodes via the real decode statement
	// (loadCheckpoint in spill.go: `json.Unmarshal(v.Data, &doc)` then
	// doc.State.normalize()).
	var doc checkpointDoc
	require.NoError(t, json.Unmarshal([]byte(checkpointJSONv1), &doc))
	require.NotNil(t, doc.State)
	doc.State.normalize()

	// 3. Field-by-field: every durable field round-trips to the value that
	// produced the fixture.
	want := wantCheckpointState()
	assert.Equal(t, wantCheckpointUID, doc.UID)
	assert.Equal(t, want.Spec, doc.State.Spec)
	assert.Equal(t, want.Input, doc.State.Input)
	assert.Equal(t, want.Current, doc.State.Current)
	assert.Equal(t, want.Doc, doc.State.Doc)
	assert.Equal(t, want.Attempts, doc.State.Attempts)
	assert.Equal(t, want.Results, doc.State.Results)
	assert.Equal(t, want.TimersFired, doc.State.TimersFired)
	assert.Equal(t, want.Terminal, doc.State.Terminal)
	assert.Equal(t, want.ErrorType, doc.State.ErrorType)
	assert.Equal(t, want.Cause, doc.State.Cause)
	assert.True(t, want.StartedAt.Equal(doc.State.StartedAt), "startedAt: want %s got %s", want.StartedAt, doc.State.StartedAt)
	assert.Equal(t, want.LastSeq, doc.State.LastSeq)
	require.Len(t, doc.State.Recent, len(want.Recent))
	for i := range want.Recent {
		assert.Equal(t, want.Recent[i].Seq, doc.State.Recent[i].Seq)
		assert.Equal(t, want.Recent[i].Type, doc.State.Recent[i].Type)
		assert.Equal(t, want.Recent[i].Note, doc.State.Recent[i].Note)
		assert.True(t, want.Recent[i].At.Time.Equal(doc.State.Recent[i].At.Time))
	}
}

// wantFailedEvent is the representative event payload used by
// TestEventPayloadCompat_V1RoundTrip: a StepFailed inside a parallel branch,
// exercising Branch/Region (workflowbranch.tla routing) alongside the
// ordinary error fields.
func wantFailedEvent() Event {
	return Event{
		Type:      EvStepFailed,
		State:     "task2",
		Branch:    "1",
		Region:    "fanout@3",
		Attempt:   2,
		ErrorType: "Fission.FunctionError",
		Cause:     json.RawMessage(`{"message":"boom","code":500}`),
		InputHash: "sha256:deadbeef",
	}
}

// eventJSONv1 is the exact byte sequence json.Marshal(wantFailedEvent())
// produces TODAY (verified below).
//
// compat gate for the json/v2 migration — old durable bytes must keep
// decoding; if this fails after a migration commit, add compat options at
// the decode site, do not update the fixture. (As with checkpointJSONv1,
// the marshal-equality half is a canary that legitimately fires on additive
// Event schema changes; only the decode half is the hard gate.)
const eventJSONv1 = `{"type":"StepFailed","state":"task2","attempt":2,"branch":"1","region":"fanout@3","errorType":"Fission.FunctionError","cause":{"message":"boom","code":500},"inputHash":"sha256:deadbeef"}`

func TestEventPayloadCompat_V1RoundTrip(t *testing.T) {
	t.Parallel()

	got, err := json.Marshal(wantFailedEvent())
	require.NoError(t, err)
	require.JSONEq(t, eventJSONv1, string(got))
	assert.Equal(t, eventJSONv1, string(got), "byte-identical, not just semantically equal")

	// Decode via the real decode path: decodeEvent, exactly as the fold
	// consumes the stream (events.go).
	se := statestore.Event{Seq: 5, Type: string(EvStepFailed), Payload: []byte(eventJSONv1)}
	decoded, err := decodeEvent(se)
	require.NoError(t, err)

	want := wantFailedEvent()
	assert.Equal(t, want.Type, decoded.Type)
	assert.Equal(t, want.State, decoded.State)
	assert.Equal(t, want.Branch, decoded.Branch)
	assert.Equal(t, want.Region, decoded.Region)
	assert.Equal(t, want.Attempt, decoded.Attempt)
	assert.Equal(t, want.ErrorType, decoded.ErrorType)
	assert.Equal(t, want.Cause, decoded.Cause)
	assert.Equal(t, want.InputHash, decoded.InputHash)
}

// TestClassifyErrorLenientProbe_V1Compat exercises invoker.go's
// classifyError (~line 276's `json.Unmarshal(body, &typed); err == nil &&
// typed.ErrorType != ""` branch) directly against payload shapes a real
// function response could produce. The duplicate-key and invalid-UTF-8
// cases document TODAY's lenient behavior: v1's json.Unmarshal neither
// rejects duplicate object member names (last value silently wins) nor
// invalid UTF-8 inside a JSON string (replaced with U+FFFD, not an error).
// json/v2 defaults reject both (see TestRawMessageV2Strictness_* below) —
// that divergence is exactly what a migration of this probe must account
// for with compat options, or it starts hard-failing responses this probe
// used to classify leniently.
func TestClassifyErrorLenientProbe_V1Compat(t *testing.T) {
	t.Parallel()

	const fallback = "Fission.FunctionError"

	cases := []struct {
		name          string
		body          []byte
		wantErrorType string
		wantCause     json.RawMessage
	}{
		{
			name:          "valid_typed_error_matches_probe",
			body:          []byte(`{"errorType":"Fission.PermanentError","cause":"nope"}`),
			wantErrorType: "Fission.PermanentError",
			wantCause:     json.RawMessage(`"nope"`),
		},
		{
			name:          "plain_output_falls_through_to_fallback",
			body:          []byte(`{"result":42}`),
			wantErrorType: fallback,
			wantCause:     json.RawMessage(`{"result":42}`),
		},
		{
			// v1 json.Unmarshal accepts duplicate object member names: the
			// last occurrence silently wins. The probe sees a non-empty
			// ErrorType and takes the typed branch.
			name:          "duplicate_keys_last_value_wins_lenient",
			body:          []byte(`{"errorType":"a","errorType":"b"}`),
			wantErrorType: "b",
			wantCause:     nil,
		},
		{
			// v1 json.Unmarshal accepts invalid UTF-8 inside a JSON string:
			// each invalid byte is replaced with U+FFFD rather than erroring.
			// The probe still takes the typed branch.
			name:          "invalid_utf8_replaced_not_rejected_lenient",
			body:          []byte("{\"errorType\":\"a\xff\xfeb\",\"cause\":null}"),
			wantErrorType: "a��b",
			wantCause:     json.RawMessage("null"),
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			out := classifyError(tc.body, fallback)
			assert.Equal(t, tc.wantErrorType, out.errorType)
			assert.Equal(t, tc.wantCause, out.cause)
		})
	}
}

// TestRawMessageV2Strictness_DuplicateKeys demonstrates, using
// encoding/json/v2 and encoding/json/jsontext directly against the real
// Event type, that v2 defaults reject duplicate object member names inside
// a json.RawMessage field (Cause) on both Unmarshal and Marshal, and that
// jsontext.AllowDuplicateNames(true) restores v1's lenient passthrough
// (last value wins, bytes preserved verbatim). This is why the
// workflow/DLQ document plane (checkpoints, events, the classifyError
// probe — all of which carry arbitrary caller/function JSON in RawMessage
// fields) must migrate with compat options, not with the v2 defaults.
func TestRawMessageV2Strictness_DuplicateKeys(t *testing.T) {
	t.Parallel()

	body := []byte(`{"type":"StepFailed","state":"task2","errorType":"Fission.FunctionError","cause":{"a":1,"a":2}}`)

	var strict Event
	err := jsonv2.Unmarshal(body, &strict)
	require.Error(t, err, "v2 defaults must reject duplicate object member names")
	assert.Contains(t, err.Error(), "duplicate object member name")

	var lenient Event
	err = jsonv2.Unmarshal(body, &lenient, jsontext.AllowDuplicateNames(true))
	require.NoError(t, err)
	assert.Equal(t, json.RawMessage(`{"a":1,"a":2}`), lenient.Cause,
		"AllowDuplicateNames must preserve raw bytes verbatim, matching v1's last-value-wins passthrough")

	// Marshal side: an Event already holding dup-key bytes in a RawMessage
	// field (as produced by a lenient decode, or forwarded verbatim from a
	// spilled document) must also error by default and succeed with the
	// option.
	withDup := Event{Type: EvStepFailed, Cause: json.RawMessage(`{"a":1,"a":2}`)}
	_, err = jsonv2.Marshal(withDup)
	require.Error(t, err, "v2 defaults must reject marshaling a RawMessage containing duplicate names")

	out, err := jsonv2.Marshal(withDup, jsontext.AllowDuplicateNames(true))
	require.NoError(t, err)
	assert.Contains(t, string(out), `"a":1,"a":2`, "AllowDuplicateNames must pass the bytes through on marshal too")
}

// TestRawMessageV2Strictness_InvalidUTF8 is the invalid-UTF-8 counterpart of
// TestRawMessageV2Strictness_DuplicateKeys: v2 defaults reject invalid UTF-8
// inside a json.RawMessage field on both Unmarshal and Marshal, and
// jsontext.AllowInvalidUTF8(true) restores v1's passthrough.
func TestRawMessageV2Strictness_InvalidUTF8(t *testing.T) {
	t.Parallel()

	body := []byte("{\"type\":\"StepFailed\",\"state\":\"task2\",\"cause\":\"a\xff\xfeb\"}")

	var strict Event
	err := jsonv2.Unmarshal(body, &strict)
	require.Error(t, err, "v2 defaults must reject invalid UTF-8 inside a JSON string")
	assert.Contains(t, err.Error(), "invalid UTF-8")

	var lenient Event
	err = jsonv2.Unmarshal(body, &lenient, jsontext.AllowInvalidUTF8(true))
	require.NoError(t, err)
	assert.Equal(t, []byte("\"a\xff\xfeb\""), []byte(lenient.Cause),
		"AllowInvalidUTF8 must preserve the invalid bytes verbatim, not substitute U+FFFD")

	withBadUTF8 := Event{Type: EvStepFailed, Cause: json.RawMessage("\"a\xff\xfeb\"")}
	_, err = jsonv2.Marshal(withBadUTF8)
	require.Error(t, err, "v2 defaults must reject marshaling a RawMessage containing invalid UTF-8")

	// Marshal's AllowInvalidUTF8 is NOT symmetric with Unmarshal's: it stops
	// the error, but it substitutes U+FFFD for each invalid byte rather than
	// passing the original bytes through. Re-marshaling a leniently-decoded
	// RawMessage does not reproduce the original wire bytes — a real gap for
	// any code path that decodes leniently then re-encodes (e.g. re-spilling
	// a document) under v2.
	out, err := jsonv2.Marshal(withBadUTF8, jsontext.AllowInvalidUTF8(true))
	require.NoError(t, err)
	assert.Contains(t, string(out), "\"cause\":\"a��b\"",
		"AllowInvalidUTF8 on Marshal substitutes U+FFFD; it does not pass invalid bytes through unlike Unmarshal")
}
