FROM alpine:3.10 as base
RUN apk add --update ca-certificates

FROM golang:1.11-alpine as builder
RUN apk add bash ca-certificates git gcc g++ libc-dev

ARG GOPKG=github.com/fission/fission

ENV GO111MODULE=on

WORKDIR /go/src/${GOPKG}

# To reuse build cache, copy go.mod & go.sum and download dependencies first.
COPY go.* ./

RUN go mod download

# Copy whole fission directory to work dir
COPY ./ ./

WORKDIR /go/src/${GOPKG}/cmd/preupgradechecks

ARG GITCOMMIT=unknown
# E.g. GITCOMMIT=$(git rev-parse HEAD)

ARG BUILDVERSION=unknown
# E.g. BUILDVERSION=$(git rev-parse HEAD)

ARG BUILDDATE=unknown
# E.g. BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -o /go/bin/pre-upgrade-checks \
    -gcflags=-trimpath=$GOPATH \
    -asmflags=-trimpath=$GOPATH \
    -ldflags "-X github.com/fission/fission/pkg/info.GitCommit=${GITCOMMIT} -X github.com/fission/fission/pkg/info.BuildDate=${BUILDDATE} -X github.com/fission/fission/pkg/info.Version=${BUILDVERSION}"

FROM base
COPY --from=builder /go/bin/pre-upgrade-checks /

ENTRYPOINT ["/pre-upgrade-checks"]
EXPOSE 8001
