# SPDX-FileCopyrightText: The Fission Authors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.functionState.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-statesvc
  labels:
    svc: statesvc
    application: fission-statesvc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- end }}
