# SPDX-FileCopyrightText: The Fission Authors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.functionState.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-statesvc
  namespace: {{ .Release.Namespace }}
  {{- include "fission.saAnnotationsBlock" (dict "root" . "component" "statesvc") }}
  labels:
    svc: statesvc
    application: fission-statesvc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- with include "fission.saLabels" (dict "root" . "component" "statesvc") }}{{ . | nindent 4 }}{{- end }}
{{- end }}
