name: Lint and Unit tests

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**/Dockerfile*"
      - "**.sh"
      - "**.py"
      - Makefile
      - hack/license-header.tmpl
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**/Dockerfile*"
      - "**.sh"
      - "**.py"
      - Makefile
      - hack/license-header.tmpl

env:
  GOLANGCI_LINT_VERSION: v2.12.2
  GOLANGCI_LINT_TIMEOUT: 5m

permissions:
  contents: read

concurrency:
  group: fission-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    runs-on: ubuntu-24.04
    # if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Verify dependencies
        run: |
          go mod verify
          go mod download
          make verify-gomod

      - name: Check license headers
        run: make license-check

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          skip-cache: true
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout=${{ env.GOLANGCI_LINT_TIMEOUT }}

      - name: Detect git changes
        if: always()
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '❌ \033[0;31m. Fix lint changes.\033[0m'
            git diff --color
            exit 1
          else
            echo '✔ No issues detected. Have a nice day :-)'
          fi

      - name: Run unit tests
        run: ./hack/runtests.sh

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          file: ./coverage.txt
