name: Create Draft release
on:
  push:
    tags:
      - v1.**
      - v2.**

env:
  KIND_VERSION: v0.30.0
  KIND_NODE_IMAGE_TAG: v1.28.15
  KIND_CLUSTER_NAME: kind
  COSIGN_VERSION: v3.0.3

jobs:
  create-draft-release:
    name: Create Draft Release with Goreleaser
    outputs:
      ghcr_images: ${{ steps.image.outputs.ghcr_images }}
      version: ${{ steps.get_version.outputs.VERSION }}
    permissions:
      contents: write # for goreleaser/goreleaser-action to create a GitHub release
      packages: write # for goreleaser/goreleaser-action to upload artifacts to GitHub Packages
      id-token: write # for cosign to sign the image and binary
      attestations: write # for goreleaser/goreleaser-action to upload attestations
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7.1.0
        with:
          install-only: true
          version: "~> v2"

      - name: Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          node_image: kindest/node:${{ env.KIND_NODE_IMAGE_TAG }}
          version: ${{ env.KIND_VERSION }}
          config: kind.yaml
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to ghcr.io
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Check cosign install!
        run: cosign version

      - uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 #v0.24.0

      - name: Generate yaml for manifest, Minikube and Openshift installation
        run: ${GITHUB_WORKSPACE}/hack/build-yaml.sh $VERSION
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        shell: bash

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7.1.0
        with:
          version: "~> v2"
          args: release
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_CLI_EXPERIMENTAL: "enabled"

      # Attest binary artifacts
      # https://goreleaser.com/customization/attestations/
      - name: Attest binary artifacts
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-checksums: ./dist/checksums.txt

      - name: Image digest
        id: image
        env:
          ARTIFACTS: "${{ steps.goreleaser.outputs.artifacts }}"
        run: |
          set -euo pipefail
          image_and_digest=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Docker Image") | {name, "digest": (.extra.Digest // .extra.Checksum)} | select(.digest) | {name} + {digest} | join("@") | sub("^sha256:";"")' | grep -v latest)
          ghcr_images=$(echo "${image_and_digest}" | grep ghcr.io | jq -R -s -c '
            split("\n")
            | map(select(. != ""))
            | map(
                split("@")
                | {
                    "image": .[0] | split(":")[0],
                    "checksum": .[1]
                  }
              )')
          echo "ghcr_images=$ghcr_images" >> "$GITHUB_OUTPUT"

  image-sbom-provenance-ghcr:
    name: Create SBOM & Provenance for container images
    # Goreleaser does not support generating SBOM for container images.
    needs: [create-draft-release]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include: ${{ fromJson(needs.create-draft-release.outputs.ghcr_images) }}
    permissions:
      actions: write
      id-token: write
      packages: write
      attestations: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy in fs mode to generate SBOM
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: "fs"
          format: "spdx-json"
          output: "sbom.spdx.json"
      - name: Attest SBOM for image
        uses: actions/attest-sbom@c604332985a26aa8cf1bdc465b92731239ec6b9e # v4.1.0
        with:
          sbom-path: sbom.spdx.json
          subject-name: ${{ fromJson(toJson(matrix)).image }}
          subject-digest: ${{ fromJson(toJson(matrix)).checksum }}
          push-to-registry: true
      - name: Attest provenance for image
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: ${{ fromJson(toJson(matrix)).image }}
          subject-digest: ${{ fromJson(toJson(matrix)).checksum }}
          push-to-registry: true

  image-provenance-verification-with-cosign:
    name: Verify Image Provenance
    needs: [create-draft-release, image-sbom-provenance-ghcr]
    strategy:
      matrix:
        include: ${{ fromJson(needs.create-draft-release.outputs.ghcr_images) }}
    runs-on: ubuntu-24.04
    permissions: read-all
    steps:
      - name: Login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Verify image
        env:
          IMAGE: ${{ fromJson(toJson(matrix)).image }}
          DIGEST: ${{ fromJson(toJson(matrix)).checksum }}
        run: |
          echo "Verifying $IMAGE@$DIGEST"
          cosign verify-attestation \
             --type https://slsa.dev/provenance/v1 \
             --certificate-oidc-issuer https://token.actions.githubusercontent.com \
             --certificate-identity-regexp '^https://github.com/fission/fission/.github/workflows/release.yaml@refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(?:-rc[0-9]+)?$' \
             $IMAGE@$DIGEST
