name: Create Draft release
on:
  push:
    tags:
      - v1.**
      - v2.**

env:
  KIND_VERSION: v0.32.0
  KIND_NODE_IMAGE_TAG: v1.32.11
  KIND_CLUSTER_NAME: kind
  COSIGN_VERSION: v3.1.1

permissions:
  contents: read

jobs:
  create-draft-release:
    name: Create Draft Release with Goreleaser
    outputs:
      ghcr_images: ${{ steps.image.outputs.ghcr_images }}
      version: ${{ steps.get_version.outputs.VERSION }}
    permissions:
      contents: write # for goreleaser/goreleaser-action to create a GitHub release
      packages: write # for goreleaser/goreleaser-action to upload artifacts to GitHub Packages
      id-token: write # for cosign to sign the image and binary
      attestations: write # for goreleaser/goreleaser-action to upload attestations
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          install-only: true
          version: "~> v2"

      - name: Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          node_image: kindest/node:${{ env.KIND_NODE_IMAGE_TAG }}
          version: ${{ env.KIND_VERSION }}
          config: kind.yaml
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to ghcr.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Check cosign install!
        run: cosign version

      - uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 #v0.24.0

      - name: Generate yaml for manifest, Minikube and Openshift installation
        run: ${GITHUB_WORKSPACE}/hack/build-yaml.sh $VERSION
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        shell: bash

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: release
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_CLI_EXPERIMENTAL: "enabled"

      # Attest binary artifacts
      # https://goreleaser.com/customization/attestations/
      - name: Attest binary artifacts
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-checksums: ./dist/checksums.txt

      - name: Image digest
        id: image
        env:
          ARTIFACTS: "${{ steps.goreleaser.outputs.artifacts }}"
        run: |
          set -euo pipefail
          image_and_digest=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Docker Image") | {name, "digest": (.extra.Digest // .extra.Checksum)} | select(.digest) | {name} + {digest} | join("@") | sub("^sha256:";"")' | grep -v latest)
          ghcr_images=$(echo "${image_and_digest}" | grep ghcr.io | jq -R -s -c '
            split("\n")
            | map(select(. != ""))
            | map(
                split("@")
                | {
                    "image": .[0] | split(":")[0],
                    "checksum": .[1]
                  }
              )')
          echo "ghcr_images=$ghcr_images" >> "$GITHUB_OUTPUT"

  image-sbom-provenance-ghcr:
    name: Create SBOM & Provenance for container images
    # Goreleaser does not support generating SBOM for container images.
    needs: [create-draft-release]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include: ${{ fromJson(needs.create-draft-release.outputs.ghcr_images) }}
    permissions:
      id-token: write
      packages: write
      attestations: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy in fs mode to generate SBOM
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "fs"
          format: "spdx-json"
          output: "sbom.spdx.json"
      - name: Attest SBOM for image
        uses: actions/attest-sbom@c604332985a26aa8cf1bdc465b92731239ec6b9e # v4.1.0
        with:
          sbom-path: sbom.spdx.json
          subject-name: ${{ fromJson(toJson(matrix)).image }}
          subject-digest: ${{ fromJson(toJson(matrix)).checksum }}
          push-to-registry: true
      - name: Attest provenance for image
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-name: ${{ fromJson(toJson(matrix)).image }}
          subject-digest: ${{ fromJson(toJson(matrix)).checksum }}
          push-to-registry: true

  image-provenance-verification-with-cosign:
    name: Verify Image Provenance
    needs: [create-draft-release, image-sbom-provenance-ghcr]
    strategy:
      matrix:
        include: ${{ fromJson(needs.create-draft-release.outputs.ghcr_images) }}
    runs-on: ubuntu-24.04
    permissions: read-all
    steps:
      - name: Login
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Verify image
        env:
          IMAGE: ${{ fromJson(toJson(matrix)).image }}
          DIGEST: ${{ fromJson(toJson(matrix)).checksum }}
        run: |
          echo "Verifying $IMAGE@$DIGEST"
          cosign verify-attestation \
             --type https://slsa.dev/provenance/v1 \
             --certificate-oidc-issuer https://token.actions.githubusercontent.com \
             --certificate-identity-regexp '^https://github.com/fission/fission/.github/workflows/release.yaml@refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(?:-rc[0-9]+)?$' \
             $IMAGE@$DIGEST
