name: Fission CI upgrade

on:
  push:
    branches:
      - main
      - '!dependabot/**'
    paths:
      - "**.go"
      - "charts/**"
      - "test/**"
      - go.mod
      - go.sum
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "charts/**"
      - "test/**"
      - go.mod
      - go.sum

env:
  HELM_VERSION: v3.19.0
  KIND_VERSION: v0.30.0
  KIND_CLUSTER_NAME: kind

permissions:
  contents: read

concurrency:
  group: fission-upgrade-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upgrade-test:
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    strategy:
      fail-fast: false
      matrix:
        kindversion: ["v1.31.12"]
        os: [ubuntu-24.04]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout action sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Setup Helm
        uses: Azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Setup Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          node_image: kindest/node:${{ matrix.kindversion }}
          version: ${{ env.KIND_VERSION }}
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7.2.1
        with:
          install-only: true
          version: "~> v2"

      - name: Setup kubectl & fetch node information
        run: |
          kubectl cluster-info --context kind-${{ env.KIND_CLUSTER_NAME }}
          kubectl get nodes
          kubectl get storageclasses.storage.k8s.io
          kubectl config use-context kind-${{ env.KIND_CLUSTER_NAME }}
          kubectl config set-context --current --namespace=default
          kubectl config view

      - name: Dump system info
        run: |
          source ./test/upgrade_test/fission_objects.sh dump_system_info

      - name: Install and configure previous stable fission
        run: |
          source ./test/upgrade_test/fission_objects.sh install_stable_release \
          && create_fission_objects \
          && test_fission_objects

      - name: Upgrade fission to latest
        run: |
          source ./test/upgrade_test/fission_objects.sh build_docker_images \
          && kind_image_load \
          && install_current_release \
          && install_fission_cli

      - name: Test previously created fission objects with new release
        timeout-minutes: 10
        run: |
          source ./test/upgrade_test/fission_objects.sh test_fission_objects

      - name: Collect Fission Dump
        if: ${{ always() }}
        run: |
          command -v fission && fission support dump

      - name: Kind export logs
        if: ${{ always() }}
        run: |
          kind export logs --name ${{ env.KIND_CLUSTER_NAME }} kind-logs

      - name: Archive fission dump
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: fission-dump-${{ github.run_id }}-${{ matrix.kindversion }}
          path: fission-dump/*.zip
          retention-days: 5

      - name: Archive kind logs
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: kind-logs-${{ github.run_id }}-${{ matrix.kindversion }}
          path: kind-logs/*
          retention-days: 5
